UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodrealitycheck.com/wp-content/uploads/2025/12/E320-Butylated-Hydroxyanisole-BHA-768x768.png' WHERE id = '63aed9d2-a419-4561-aa8d-13f36eb0f03d';
UPDATE ingredient SET public_summary = 'Sodium benzoate, also known as benzoate of soda, is the sodium salt of benzoic acid, widely used as a food preservative (with an E number of E211) and a pickling agent. It appears as a white crystalline chemical with the formula C6H5COONa.', image_url = 'https://www.cnchemsino.com/foodingredients/wp-content/uploads/2025/10/Wholesale-Sodium-Benzoate-for-Food-Processing.jpg' WHERE id = '236dd9fc-ac28-4799-93e5-3ba0581be6c1';
UPDATE ingredient SET public_summary = 'Sodium is a chemical element; it has symbol Na (from Neo-Latin natrium) and atomic number 11. It is a soft, silvery-white, highly reactive metal. Sodium is an alkali metal, being in group 1 of the periodic table. Its only stable isotope is 23Na. The free metal does not occur in nature and must be prepared from compounds. Sodium is the sixth–most abundant element in the Earth''s crust and exists in numerous minerals such as feldspars, sodalite, and halite (NaCl). Many salts of sodium are highly water-soluble: sodium ions have been leached by the action of water from the Earth''s minerals over eons, and thus sodium and chlorine are the most common dissolved elements by weight in the oceans.
Sodium was first isolated by Humphry Davy in 1807 by the electrolysis of sodium hydroxide. Among many other useful sodium compounds, sodium hydroxide (lye) is used in soap manufacture, and sodium chloride (edible salt) is a de-icing agent and a nutrient for animals including humans.
Sodium is an essential element for all animals and some plants. Sodium ions are the major cation in the extracellular fluid (ECF) and as such are the major contributor to the ECF osmotic pressure. Animal cells actively pump sodium ions out of the cells by means of the sodium–potassium pump, an enzyme complex embedded in the cell membrane, in order to maintain a roughly ten-times higher concentration of sodium ions outside the cell than inside. In nerve cells, the sudden flow of sodium ions into the cell through voltage-gated sodium channels enables transmission of a nerve impulse in a process called the action potential.', image_url = 'https://optimisingnutrition.com/wp-content/uploads/2024/06/sodium-rich-foods.png' WHERE id = '7ddc453d-a2dd-4dec-b6e0-85ebe7cc9cf6';
UPDATE ingredient SET public_summary = 'Xanthan gum () is a polysaccharide with many industrial uses, including as a common food additive. It is an effective thickening agent and stabilizer that prevents ingredients from separating. It can be produced from simple sugars by fermentation and derives its name from the species of bacteria used, Xanthomonas campestris.', image_url = 'https://fearlessfatloss.com/wp-content/uploads/2014/01/x-is-for-xanthan-gum.jpg' WHERE id = '8b561d36-b5cd-4cef-9cd0-49aa9ce704ec';
UPDATE ingredient SET public_summary = 'A saturated fat is a type of fat: a glyceride in which the fatty acid chains have all single bonds between the carbon atoms. Glyceride fats with single bonds are called saturated because they are "saturated with" hydrogen atoms, having no C=C double bonds available to react with hydrogen. 
Saturated fats are generally solid at room temperature. All fats, both saturated and unsaturated, contain 9kcal (37.7 kJ) per gram, making them more energy dense than both proteins and carbohydrates. 
Most animal fats are saturated. The fats of plants and fish are generally unsaturated. Various foods contain different proportions of saturated and unsaturated. Many processed foods, like foods deep-fried in hydrogenated oil and sausages, are high in saturated fat content. Some store-bought baked goods are as well, especially those containing partially hydrogenated oils. Other examples of foods containing a high proportion of saturated fat and dietary cholesterol include animal fat products such as lard or schmaltz, fatty meats and dairy products made with whole or reduced fat milk like yogurt, ice cream, cheese and butter. Certain vegetable products have high saturated fat content, such as coconut oil and palm kernel oil. 
Guidelines released by many medical organizations, including the World Health Organization, have advocated for reduction in the intake of saturated fat to promote health and reduce the risk from cardiovascular diseases.', image_url = 'https://s.alicdn.com/@sc02/kf/A4d40e30813a041a0a163c166d8f0afb0W.jpg' WHERE id = '15c0599e-85fc-47cf-a0f9-99da9a052207';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.shutterstock.com/shutterstock/photos/783033085/display_1500/stock-vector-infographics-vitamin-c-or-ascorbic-acid-food-sources-top-natural-organic-vegetables-fruits-783033085.jpg' WHERE id = '554a01cd-e034-42dd-8d21-49190540f16b';
UPDATE ingredient SET public_summary = 'Maltodextrin is a name shared by two different families of chemicals. Both families are glucose polymers (also called dextrose polymers or dextrins), but have little chemical or nutritional similarity.
The digestible maltodextrins (or simply maltodextrins) are  manufactured as white solids derived from chemical processing of plant starches. They are used as food additives, which are digested rapidly, providing glucose as food energy. They are generally recognized as safe (GRAS) for food and beverage manufacturing in numerous products. Due to their rapid production of glucose, digestible maltodextrins are potential risks for people with diabetes.
The digestion-resistant maltodextrins (also called resistant maltodextrins) are defined as nutritional food additives due to their ability upon fermentation in the colon to yield short-chain fatty acids, which contribute to gastrointestinal health. Digestion-resistant maltodextrins are also white solids resulting from the chemical processing of plant starches, but are processed using methods specifically to be resistant to digestion. They are used as ingredients in many consumer products, such as low-calorie sweeteners, and are considered GRAS.
Consumers may find the shared name for different maltodextrin food additives to be confusing.', image_url = 'https://foodmanifest.com/wp-content/uploads/2024/08/20171109151513_51903.jpg' WHERE id = 'cff41e26-ce40-4468-b0a2-f3ae54ab805f';
UPDATE ingredient SET public_summary = 'Aspartame is an artificial, non-saccharide sweetener commonly used as a sugar substitute in foods and beverages. It is 200 times sweeter than sucrose, and is a methyl ester of the aspartic acid/phenylalanine dipeptide with brand names NutraSweet, Equal, and Canderel. Discovered in 1965, aspartame was approved by the US Food and Drug Administration (FDA) in 1974 and re-approved in 1981 after its initial approval was briefly revoked.
Aspartame is one of the most studied food additives in the human food supply. Reviews by over 100 governmental regulatory bodies found the ingredient safe for consumption at the normal acceptable daily intake limit. A number of health organizations such as the American Heart Association, American Diabetes Association, and American Cancer Society are supportive of its use consistent with other approved low-calorie sweeteners.', image_url = 'http://foodmanifest.com/wp-content/uploads/2025/02/Examples-of-food-containing-Aspartame-300x234.webp' WHERE id = 'ea70f18b-8e00-4a59-9472-e63f66b2f7f8';
UPDATE ingredient SET public_summary = 'Potassium sorbate is the potassium salt of sorbic acid, structural formula CH3CH=CH−CH=CH−CO2K.  It is a white salt that is very soluble in water (58.2% at 20 °C).  It is primarily used as a food preservative (E number 202). Potassium sorbate is effective in a variety of applications including food, wine, and personal care products. While sorbic acid occurs naturally in rowan and hippophae berries, virtually all of the world''s supply of sorbic acid, from which potassium sorbate is derived, is manufactured synthetically.', image_url = 'https://image.made-in-china.com/2f0j00skEWtVqjHLUS/Food-Ingredient-Potassium-Sorbate-Granular-E202-in-Food.jpg' WHERE id = '810d7d24-3d3b-4ec8-8ca9-8983f28603e7';
UPDATE ingredient SET public_summary = 'Erythritol (, US: ) is an organic compound, the naturally occurring achiral meso four-carbon sugar alcohol (or polyol). It is the reduced form of either D- or L-erythrose and one of the two reduced forms of erythrulose. It is used as a food additive and sugar substitute. It is synthesized from corn using enzymes and fermentation. Its formula is C4H10O4, or HO(CH2)(CHOH)2(CH2)OH.
Erythritol is 60–70% as sweet as table sugar. However, erythritol is almost completely noncaloric and does not affect blood sugar or cause tooth decay. Japanese companies pioneered the commercial development of erythritol as a sweetener in the 1990s.', image_url = 'https://cdn.prod.website-files.com/62e18da95149ec2ee0d87b5b/641446775aed666c19e1962f_2-natural-sources-of-erythritol.webp' WHERE id = 'e570578e-4d86-4616-ad0e-4b4b1593cd92';
UPDATE ingredient SET public_summary = 'Sugar is a class of sweet-tasting, soluble carbohydrates, many of which are used in food. Simple sugars, also called monosaccharides, include glucose, fructose and galactose. Compound sugars, also called disaccharides or double sugars, are molecules made of two bonded monosaccharides; common examples are sucrose (glucose + fructose), lactose (glucose + galactose) and maltose (two molecules of glucose). White sugar is almost pure sucrose. During digestion, compound sugars are hydrolysed into simple sugars.
Longer chains of saccharides are not regarded as sugars, and are called oligosaccharides or polysaccharides. Starch is a glucose polymer found in plants – the most abundant source of energy in human food. Some other chemical substances, such as ethylene glycol, glycerol and sugar alcohols, may have a sweet taste, but are not classified as sugar.
Sugars are found in the tissues of most plants. Honey and fruits are abundant natural sources of simple sugars. Sucrose is especially concentrated in sugarcane and sugar beet, making them efficient for commercial extraction to make refined sugar. In 2016 the combined world production of those two crops was about two billion tonnes. Maltose may be produced by malting grain. Lactose is the only sugar that cannot be extracted from plants, as it occurs only in milk, including human breast milk, and in some dairy products. A cheap source of sugar is corn syrup, industrially produced by converting corn starch into sugars, such as maltose, fructose and glucose.
Sucrose is used in prepared foods (e.g., cookies and cakes), is added to commercially available ultra-processed food and beverages, and is used as a sweetener for foods (e.g., toast and cereal) and beverages (e.g., coffee and tea). Globally, on average, a person consumes about 24 kilograms (53 pounds) of sugar each year. North and South Americans consume up to 50 kg (110 lb), and Africans consume under 20 kg (44 lb).
The use of added sugar in food and beverage manufacturing is a concern for elevated calorie intake, which is associated with an increased risk of several diseases, such as obesity, diabetes and cardiovascular disorders. In 2015 the World Health Organization recommended that adults and children should reduce their intake of free sugars to less than 10% of their total energy intake, encouraging a reduction to below 5%.', image_url = 'https://med.libretexts.org/@api/deki/files/21241/image4-2-1.png?revision=1' WHERE id = 'f5a024ee-a297-4774-a5aa-891725ea8698';
UPDATE ingredient SET public_summary = 'Carrageenans or carrageenins ( KARR-ə-GHEE-nins; from Irish  carraigín ''sea moss'') are a variety of natural linear sulfated polysaccharides. They are extracted from red edible seaweeds, of the family Solieriaceae. Carrageenans are widely used in the food industry for their gelling, thickening, and stabilizing properties. Their main application is in dairy and meat products, due to their strong binding to food proteins. Carrageenans have emerged as a promising candidate in tissue engineering and regenerative medicine applications as they resemble animal glycosaminoglycans (GAGs). They are used for tissue engineering, wound coverage, and drug delivery.
Carrageenans contain 15–40% ester-sulfate content, which makes them anionic polysaccharides. They can be mainly categorized into three classes based on their sulfate content. Kappa-carrageenan has one sulfate group per disaccharide, iota-carrageenan has two, and lambda-carrageenan has three.
A common seaweed used for manufacturing the hydrophilic colloids to produce carrageenan is Chondrus crispus (Irish moss), which is a dark red, parsley-like alga that grows attached to rocks. Gelatinous extracts of C. crispus have been used as food additives since approximately the fifteenth century. Carrageenan is a vegetarian and vegan alternative to gelatin in some applications, and is used to replace gelatin in confectionery and other food.
The first industrial commercial cultivation of Eucheuma and Kappaphycus spp. for carrageenan was developed in the Philippines in the mid-1970s. The global top producers of carrageenan are the Philippines and Indonesia. Carrageenan, along with agar, is used to produce traditional jelly desserts in the Philippines called gulaman.
No clinical evidence establishes carrageenan as an unsafe food ingredient, mainly because its fate after digestion is inadequately determined.', image_url = 'https://ingreland.com/wp-content/uploads/2025/12/Kappa-Carageenan.png' WHERE id = '5920c511-c596-49d0-aa36-12b3d7610835';
UPDATE ingredient SET public_summary = 'Monosodium glutamate (MSG), also known as sodium glutamate,  is a sodium salt of glutamic acid.  MSG is found naturally in some foods including tomatoes and cheese in this glutamic acid form, and is used in cooking as a flavor enhancer that intensifies the umami flavor of food, as naturally occurring glutamate does in foods such as stews and meat soups.
MSG was first extracted in 1908 by Japanese biochemist Kikunae Ikeda, who tried to isolate and duplicate the savory taste of kombu, an edible seaweed used as a broth (dashi)  ingredient in Japanese cuisine. It also balances, blends, and rounds the perception of other tastes.  MSG, along with disodium ribonucleotides, is commonly used and found in stock (bouillon) cubes, soups, ramen, gravy, stews, condiments, savory snacks, etc.
The U.S. Food and Drug Administration has given MSG its generally recognized as safe (GRAS) designation. It is a popular misconception that MSG can cause headaches and other feelings of discomfort, known as "Chinese restaurant syndrome". Several blinded studies show no such effects when MSG is combined with food in normal concentrations, and are inconclusive when MSG is added to broth in large concentrations. The European Union classifies it as a food additive permitted in certain foods and subject to quantitative limits. MSG has the HS code 2922.42 and the E number E621.', image_url = 'https://images.healthonics.healthcare/wp-content/uploads/2020/09/MONOSODIUM-GLUTAMATE-1.webp' WHERE id = 'd9dd6f22-0122-4990-8fea-db87d82fe40d';
UPDATE ingredient SET public_summary = 'Guar gum, also called guaran, is a galactomannan polysaccharide extracted from guar beans that has thickening and stabilizing properties useful in food, feed, and industrial applications. The guar seeds are mechanically dehusked, hydrated, milled and screened according to application. It is typically produced as a free-flowing, off-white powder.', image_url = 'https://www.microingredients.com/cdn/shop/files/GuarGum_2_1800x1800.jpg?v=1699036884' WHERE id = '0fdc781a-78db-4f64-b827-dfbf17b50f6b';
UPDATE ingredient SET public_summary = 'Sucralose is an artificial sweetener and sugar substitute. In the European Union, it is also known under the E number E955. It is produced by chlorination of sucrose, selectively replacing three of the hydroxy groups. Sucralose is about 600 times sweeter than sucrose (table sugar), three times as sweet as both aspartame and acesulfame potassium, and twice as sweet as sodium saccharin.
The commercial success of sucralose-based products stems from its favorable comparison to other low-calorie sweeteners in terms of taste, stability, and safety.', image_url = 'https://draxe.com/wp-content/uploads/2018/11/Sucralose-Infographic-2-768x2488.jpg' WHERE id = '0432013c-c11d-44de-b2ae-d1f5f1efca23';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.daynatural.com/wp-content/uploads/2024/08/Dosage-of-Steviain-different-products.jpg' WHERE id = '6ea75b63-1bad-4f5a-bbb9-4aa0e2128bd1';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://www.lilsipper.com/wp-content/uploads/2018/04/2BA8B644-0B2E-474D-B215-F35A29D1EE05.jpg' WHERE id = '71690b52-d934-4659-b798-28c1820e7f2d';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://zioadditives.com/wp-content/uploads/2026/03/BHT10-ezgif.com-jpg-to-webp-converter.webp' WHERE id = '06e9f4ec-0d2a-458d-b9a0-128507a9872a';
UPDATE ingredient SET public_summary = 'Carmine () – also called cochineal (when it is extracted from the cochineal insect), cochineal extract, crimson lake, or carmine lake –  is a pigment of a bright-red color obtained from the aluminium complex derived from carminic acid. Specific code names for the pigment include natural red 4, C.I. 75470, or E120. Carmine is also a general term for a particularly deep-red color.', image_url = 'https://imbarex.com/wp-content/uploads/2024/09/DALL·E-2024-09-16-17.41.03-A-vibrant-engaging-cover-photo-for-an-article-comparing-Red-40-and-Carmine-food-dyes.-The-image-should-feature-two-contrasting-visuals_-on-one-side-.webp' WHERE id = '862c60e5-5bda-463a-8f82-ed575dc4f9c1';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/736x/58/0a/d2/580ad2f40acc35f0d2f8c312b6010569.jpg' WHERE id = '2b6e98fe-be69-4f49-afb9-14c260c565c0';
UPDATE ingredient SET public_summary = 'In food science and food engineering, high-fructose corn syrup (HFCS), glucose–fructose syrup or isoglucose is a sweetener made from corn, typically produced via industrial applications of enzyme. Conventional corn syrup is first produced by enzymatic break down of corn starch into glucose, part of which is further converted into fructose using D-xylose isomerase. HFCS was first marketed in the early 1970s by the Clinton Corn Processing Company, together with the Japanese Agency of Industrial Science and Technology, where the enzyme was discovered in 1965.
As a sweetener, HFCS is often compared to granulated sugar, but manufacturing advantages of HFCS over sugar include that it is  cheaper, especially as it can be directly pumped with less labor involved. "HFCS 42" and "HFCS 55" refer to dry weight fructose compositions of 42% and 55% respectively, the rest being glucose. HFCS 42 is mainly used for processed foods and breakfast cereals, whereas HFCS 55 is used mostly for production of soft drinks.
The United States Food and Drug Administration (FDA) states that it is not aware of evidence showing that HFCS is less safe than traditional sweeteners such as sucrose and honey. As of 2026, there is no scientific consensus that fructose or HFCS impacts cardiometabolic health when substituted for sucrose. Uses and exports of HFCS from American producers have grown steadily during the early 21st century.', image_url = 'https://i.dailymail.co.uk/1s/2024/02/15/21/81328203-13089151-image-a-22_1708031215816.jpg' WHERE id = '7e8e2d0e-0420-4f71-98e0-1c71ac91aeb4';
UPDATE ingredient SET public_summary = 'Titanium dioxide, also known as titanium(IV) oxide or titania , is the inorganic compound derived from titanium with the chemical formula TiO2. When used as a pigment, it is called titanium white, Pigment White 6 (PW6), or CI 77891. It is a white solid that is insoluble in water, although mineral forms can appear black. As a pigment, it has a wide range of applications, including paint, sunscreen, and food coloring. When used as a food coloring, it has E number E171. World production in 2014 exceeded 9 million tonnes. It has been estimated that titanium dioxide is used in two-thirds of all pigments, and pigments based on the oxide have been valued at a price of $13.2 billion.', image_url = 'https://wellfitinsider.com/wp-content/uploads/2026/01/How-to-Identify-Titanium-Dioxide-on-Ingredient-Labels-1024x683.jpg' WHERE id = 'b0456a8e-6ac7-4506-b736-74596f5e0116';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://easybuyingredients.com/wp-content/uploads/2023/09/Soy-Lecithin-The-Secret-Ingredient-Revolutionizing-the-Food-Industry-and-its-Surprising-Uses.png' WHERE id = '3fa52e80-7ee3-4248-9792-188b166a7bb0';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://huhuly.com/wp-content/uploads/2026/03/ingredient-label-close-up-showing-allura-red-ac-and-red-40-lake-at-the-bottom-of-the-list-1024x559.jpeg' WHERE id = 'a0168a34-bde0-49e1-997e-79623490a16f';