UPDATE ingredient SET public_summary = 'Sugar is a class of sweet-tasting, soluble carbohydrates, many of which are used in food. Simple sugars, also called monosaccharides, include glucose, fructose and galactose. Compound sugars, also called disaccharides or double sugars, are molecules made of two bonded monosaccharides; common examples are sucrose (glucose + fructose), lactose (glucose + galactose) and maltose (two molecules of glucose). White sugar is almost pure sucrose. During digestion, compound sugars are hydrolysed into simple sugars.
Longer chains of saccharides are not regarded as sugars, and are called oligosaccharides or polysaccharides. Starch is a glucose polymer found in plants – the most abundant source of energy in human food. Some other chemical substances, such as ethylene glycol, glycerol and sugar alcohols, may have a sweet taste, but are not classified as sugar.
Sugars are found in the tissues of most plants. Honey and fruits are abundant natural sources of simple sugars. Sucrose is especially concentrated in sugarcane and sugar beet, making them efficient for commercial extraction to make refined sugar. In 2016 the combined world production of those two crops was about two billion tonnes. Maltose may be produced by malting grain. Lactose is the only sugar that cannot be extracted from plants, as it occurs only in milk, including human breast milk, and in some dairy products. A cheap source of sugar is corn syrup, industrially produced by converting corn starch into sugars, such as maltose, fructose and glucose.
Sucrose is used in prepared foods (e.g., cookies and cakes), is added to commercially available ultra-processed food and beverages, and is used as a sweetener for foods (e.g., toast and cereal) and beverages (e.g., coffee and tea). Globally, on average, a person consumes about 24 kilograms (53 pounds) of sugar each year. North and South Americans consume up to 50 kg (110 lb), and Africans consume under 20 kg (44 lb).
The use of added sugar in food and beverage manufacturing is a concern for elevated calorie intake, which is associated with an increased risk of several diseases, such as obesity, diabetes and cardiovascular disorders. In 2015 the World Health Organization recommended that adults and children should reduce their intake of free sugars to less than 10% of their total energy intake, encouraging a reduction to below 5%.', image_url = 'https://thenutritionconsultant.org.uk/wp-content/uploads/2023/03/Copy-of-Sugar.png' WHERE slug = 'sugar';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://idealnutrition.com.au/wp-content/uploads/2021/06/Milk-Solids.png' WHERE slug = 'milk-solids';
UPDATE ingredient SET public_summary = 'Iodized salt (also spelled iodised salt) is table salt mixed with a minuscule amount of various iodine salts. The ingestion of iodine prevents iodine deficiency. Worldwide, iodine deficiency affects about two billion people and is the leading preventable cause of intellectual and developmental disabilities. Deficiency also causes thyroid gland problems, including endemic goitre. In many countries, iodine deficiency is a major public health problem that can be cheaply addressed by purposely adding small amounts of iodine to the sodium chloride salt.
Iodine is a micronutrient and dietary mineral that is naturally present in the food supply in some regions (especially near sea coasts) but is generally quite rare in the Earth''s crust. Where natural levels of iodine in the soil are low and vegetables do not take up the iodine, iodine added to salt provides the small but essential amount of iodine needed by humans.
An opened package of table salt with iodide may rapidly lose its iodine content in high temperature and high relative humidity conditions through the process of oxidation and iodine sublimation. Poor manufacturing techniques and storage processes can also lead to insufficient amounts of iodine in table salt.', image_url = 'https://images.openfoodfacts.org/images/products/002/460/001/0030/packaging_en.17.full.jpg' WHERE slug = 'iodised-salt';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/originals/fd/46/b5/fd46b55bf24fb7883ec65ad2cff53335.png' WHERE slug = 'water';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://pronatureorganic.com/wp-content/uploads/2026/04/Refined-Wheat-Flour-Maida-500g_0000_Front-scaled.jpg' WHERE slug = 'refined-wheat-flour-maida';
UPDATE ingredient SET public_summary = 'Cocoa solids may refer to:

Total cocoa solids, the sum of all components derived from the cocoa bean
Non-fat cocoa solids, the cocoa components remaining after the cocoa butter has been removed, primarily found in defatted cocoa powder
Chocolate liquor (or cocoa mass), the ground paste made from cocoa beans, containing both non-fat cocoa solids and cocoa butter in roughly equal proportions', image_url = 'https://yuka.io/wp-content/uploads/chocolate-en.png' WHERE slug = 'cocoa-solids';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://easybuyingredients.com/wp-content/uploads/2023/09/All-about-Liquid-Glucose-The-star-ingredient-in-the-confectionery-industry.png' WHERE slug = 'liquid-glucose';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/food-salt-ingredient-cooking-kitchen-cook-cuisine-closeup-hand-pour_996086-17499.jpg' WHERE slug = 'salt';
UPDATE ingredient SET public_summary = 'Cocoa butter, also called theobroma oil, is a pale-yellow, edible fat extracted from the cocoa bean (Theobroma  cacao). It is used to make chocolate, as well as some ointments, toiletries, and pharmaceuticals. Cocoa butter has a cocoa flavor and aroma. Its melting point is slightly below human body temperature. It is an essential ingredient of chocolate and related confectionary products. Cocoa butter does not contain butter or other animal products; it is vegan.', image_url = 'https://www.bakerpedia.com/wp-content/uploads/2018/07/Cocoa-butter_baking-ingredients-e1533080334991.jpg' WHERE slug = 'cocoa-butter';
UPDATE ingredient SET public_summary = 'Iodized salt (also spelled iodised salt) is table salt mixed with a minuscule amount of various iodine salts. The ingestion of iodine prevents iodine deficiency. Worldwide, iodine deficiency affects about two billion people and is the leading preventable cause of intellectual and developmental disabilities. Deficiency also causes thyroid gland problems, including endemic goitre. In many countries, iodine deficiency is a major public health problem that can be cheaply addressed by purposely adding small amounts of iodine to the sodium chloride salt.
Iodine is a micronutrient and dietary mineral that is naturally present in the food supply in some regions (especially near sea coasts) but is generally quite rare in the Earth''s crust. Where natural levels of iodine in the soil are low and vegetables do not take up the iodine, iodine added to salt provides the small but essential amount of iodine needed by humans.
An opened package of table salt with iodide may rapidly lose its iodine content in high temperature and high relative humidity conditions through the process of oxidation and iodine sublimation. Poor manufacturing techniques and storage processes can also lead to insufficient amounts of iodine in table salt.', image_url = 'https://images.openfoodfacts.org/images/products/002/460/001/0030/packaging_en.17.full.jpg' WHERE slug = 'iodized-salt';
UPDATE ingredient SET public_summary = 'Maltodextrin is a name shared by two different families of chemicals. Both families are glucose polymers (also called dextrose polymers or dextrins), but have little chemical or nutritional similarity.
The digestible maltodextrins (or simply maltodextrins) are  manufactured as white solids derived from chemical processing of plant starches. They are used as food additives, which are digested rapidly, providing glucose as food energy. They are generally recognized as safe (GRAS) for food and beverage manufacturing in numerous products. Due to their rapid production of glucose, digestible maltodextrins are potential risks for people with diabetes.
The digestion-resistant maltodextrins (also called resistant maltodextrins) are defined as nutritional food additives due to their ability upon fermentation in the colon to yield short-chain fatty acids, which contribute to gastrointestinal health. Digestion-resistant maltodextrins are also white solids resulting from the chemical processing of plant starches, but are processed using methods specifically to be resistant to digestion. They are used as ingredients in many consumer products, such as low-calorie sweeteners, and are considered GRAS.
Consumers may find the shared name for different maltodextrin food additives to be confusing.', image_url = 'http://foodmanifest.com/wp-content/uploads/2024/08/20171109151513_51903-300x176.jpg' WHERE slug = 'maltodextrin';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://finetechitg.com/wp-content/uploads/2025/04/prompt-a-close-up-shot-of-a-food-ing.jpg' WHERE slug = 'dextrose';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodcrumbles.com/wp-content/uploads/2023/11/untitled-14-of-25-Edit-2.jpg' WHERE slug = 'refined-palm-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://oyekirana.in/wp-content/uploads/2023/12/Acid-Regulator-330-1536x864.png' WHERE slug = 'acidity-regulator-ins-330';
UPDATE ingredient SET public_summary = 'Butter is a dairy product made from the fat and protein components of churned cream. It is a semi-solid emulsion at room temperature, consisting of approximately 81% butterfat. It is used at room temperature as a spread, melted as a condiment, and used as a fat in baking, sauce-making, pan frying, and other cooking procedures.
Most frequently made from cow''s milk, butter can also be manufactured from the milk of other mammals, including sheep, goats, buffalo, and yaks. It is made by churning milk or cream to separate the fat globules from the buttermilk. Salt has been added to butter since antiquity to help preserve it, particularly when being transported; salt may still play a preservation role but is less important today as the entire supply chain is usually refrigerated. In modern times, salt may be added for taste and food coloring for color. Rendering butter, removing the water and milk solids, produces clarified butter (including ghee), which is almost entirely butterfat.
Butter is a gel. 
Butter remains a firm solid when refrigerated but softens to a spreadable consistency at room temperature and melts to a thin liquid consistency at 32 to 35 °C (90 to 95 °F). The density of butter is 911 g/L (15+1⁄4 oz/US pt). It generally has a pale yellow color but varies from deep yellow to nearly white. Its natural, unmodified color is dependent on the source animal''s feed and genetics, but the commercial manufacturing process sometimes alters this with food colorings like annatto or carotene.
In 2023, world production of butter made from cow milk was six million tonnes, led by the United States, with 16% of the total.', image_url = 'https://www.askchefdennis.com/wp-content/uploads/2026/01/Herb-Compound-Butter-Ingredientsa_10.jpg' WHERE slug = 'butter';
UPDATE ingredient SET public_summary = 'Garlic (Allium sativum) is a species of bulbous flowering plants in the genus Allium. Its close relatives include the onion, shallot, leek, chives, Welsh onion, and Chinese onion. Garlic is native to Central Asia, northeastern Iran and the foothills of  Himalayas. It has naturalized in many other parts of the world, including Mediterranean Europe and China. There are two subspecies and hundreds of varieties of garlic.
Garlic has been used for thousands of years as a seasoning, culinary ingredient, and traditional medical remedy. It was known in many ancient civilizations, including the Babylonians, Egyptians, Jews, Romans, and Chinese, and remains significant in many cuisines and folk treatments, especially across the Mediterranean and Asia. Sulfur compounds give garlic its pungent odor and flavor. There is clinical evidence to indicate that consuming garlic has health benefits.
Garlic is cultivated in a variety of climates and countries; China was the largest producer in 2024, accounting for 73% of the world''s supply, according to the United Nations FAOSTAT.', image_url = 'https://thefoodtravellers.com/wp-content/uploads/2025/01/fresh-garlic-bulbs-and-cloves-on-wooden-board.jpg' WHERE slug = 'garlic';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.apartmenttherapy.info/image/upload/v1697728574/k/Design/2023-10/types-of-salt/Types-Of-salt_IG.jpg' WHERE slug = 'edible-common-salt';
UPDATE ingredient SET public_summary = 'Starch is a carbohydrate consisting of numerous glucose units joined by glycosidic bonds. This polysaccharide is produced by most green plants for energy storage. Worldwide, it is the most common carbohydrate in human diets, and is contained in large amounts in staple foods such as wheat, potatoes, maize (corn), rice, and cassava (manioc).
Starch is a white, tasteless and odorless powder that is insoluble in cold water or alcohol. It consists of two types of molecules: the linear and helical amylose and the branched amylopectin. Depending on the plant, starch generally contains 20–25% amylose and 75–80% amylopectin by weight. Glycogen, the energy reserve of animals, is a more highly branched version of amylopectin.
In industry, starch is often converted into sugars, for example by malting. These sugars may be fermented to produce ethanol in the manufacture of beer, whisky and biofuel. In addition, sugars produced from processed starch are used in many processed foods.
Mixing most starches in warm water produces a paste, such as wheatpaste, which can be used as a thickening, stiffening or gluing agent. The principal non-food, industrial use of starch is as an adhesive in the papermaking process. A similar paste, clothing or laundry starch, can be applied to certain textile goods before ironing to stiffen them.', image_url = 'https://s.alicdn.com/@sc02/kf/A5fef4e5f85b44d13b2313356313847d8Z.jpg' WHERE slug = 'starch';
UPDATE ingredient SET public_summary = 'The onion (Allium cepa L.Tooltip Carl Linnaeus, from Latin cepa), also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion which was classified as a separate species until 2011. The onion''s close relatives include garlic, scallion, leek, and chives.
The genus contains several other species 
cultivated for food, such as the Japanese bunching onion Allium fistulosum, the tree onion Allium × proliferum, and the Canada onion Allium canadense. The name wild onion is applied to a number of Allium species, but A. cepa is exclusively known from cultivation. Its ancestral wild original form is not known, although escapes from cultivation have become established in some regions. The onion is most frequently a biennial or a perennial plant, but is usually treated as an annual and harvested in its first growing season.
The onion plant has a fan of hollow, bluish-green leaves, and its bulb at the base of the plant begins to swell when a certain day-length is reached. The bulbs are composed of shortened, compressed, underground stems surrounded by fleshy modified scale (leaves) that envelop a central bud at the tip of the stem. In the autumn (or in spring, in the case of overwintering onions), the foliage dies down and the outer layers of the bulb become more dry, and brittle. The crop is harvested and dried and the onions are ready for use or storage. The crop is prone to attack by a number of pests and diseases, particularly the onion fly, the onion eelworm, and various fungi which can cause rotting. Some varieties of A. cepa, such as shallots and potato onions, produce multiple bulbs.
Onions are cultivated and used around the world. As a food item, they are often served raw as a vegetable or part of a prepared savoury dish, but can be eaten cooked or used to make pickles or chutneys. They are pungent when chopped and contain certain chemical substances which may irritate the eyes.', image_url = 'https://theclevermeal.com/wp-content/uploads/2022/03/onion-recipes.jpg' WHERE slug = 'onion';
UPDATE ingredient SET public_summary = 'Inverted sugar syrup is a syrup mixture of the monosaccharides glucose and fructose, made by splitting the disaccharide sucrose. This mixture''s optical rotation is opposite to that of the original sugar, which is why it is called an invert sugar. Splitting is completed through hydrolytic saccharification.
It is 30% sweeter than table sugar, and foods that contain invert sugar retain moisture better and crystallize less easily than those that use table sugar instead. Bakers, who call it invert syrup, may use it more than other sweeteners.
Other names include invert sugar, simple syrup, sugar syrup, sugar water, bar syrup, and sucrose inversion.', image_url = 'https://www.chibiotech.com/wp-content/uploads/2026/03/1-Inverted-Sugar-Syrup-CHIBIO-600x600.webp' WHERE slug = 'invert-sugar-syrup';
UPDATE ingredient SET public_summary = 'Rice flour (also rice powder) is a form of flour made from finely milled rice. It is distinct from rice starch, which is usually produced by steeping rice in lye. Rice flour is a common substitute for wheat flour. It is also used as a thickening agent in recipes that are refrigerated or frozen since it inhibits liquid separation.
Rice flour may be made from either white rice, brown rice or glutinous rice. To make the flour, the husk of rice or paddy is removed and raw rice is obtained, which is then ground to flour.', image_url = 'https://siegelingredients.com/wp-content/uploads/2023/07/products-flour-rice-iStock-473441872.jpg' WHERE slug = 'rice-flour';
UPDATE ingredient SET public_summary = 'Sunflower oil is the non-volatile oil pressed from the seeds of the sunflower (Helianthus annuus). Sunflower oil is commonly used in food as a frying oil, and in cosmetic formulations as an emollient.
Sunflower oil is primarily composed of linoleic acid, a polyunsaturated fat, and oleic acid, a monounsaturated fat. Through selective breeding and manufacturing processes, oils of differing proportions of the fatty acids are produced.  The expressed oil has a neutral taste profile. The oil contains a large amount of vitamin E.', image_url = 'https://www.plentyfoods.com.au/wp-content/uploads/2021/08/Sunflower-3.jpg' WHERE slug = 'sunflower-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'nature-identical-flavouring-substances';
UPDATE ingredient SET public_summary = 'Ginger (Zingiber officinale) is a flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine. It is an herbaceous perennial that grows annual pseudostems (false stems made of the rolled bases of leaves) about one meter tall, bearing narrow leaf blades. The inflorescences bear flowers having pale yellow petals with purple edges, and arise directly from the rhizome on separate shoots.
Ginger is in the family Zingiberaceae, which also includes turmeric (Curcuma longa), cardamom (Elettaria cardamomum), and galangal. Ginger originated in Maritime Southeast Asia and was likely domesticated first by the Austronesian peoples. It was transported with them throughout the Indo-Pacific during the Austronesian expansion (c. 5,000 BP), reaching as far as Hawaii. Ginger is one of the first spices to have been exported from Asia, arriving in Europe with the spice trade, and was used by ancient Greeks and Romans. The distantly related dicots in the genus Asarum are commonly called wild ginger because of their similar taste.
Ginger has been used in traditional medicine in China, India and Japan for centuries, and as a modern dietary supplement. Ginger may offer benefits over placebo for nausea and vomiting during pregnancy, but there is no good evidence that it helps with nausea during chemotherapy. It remains uncertain whether ginger is effective for treating any disease. In 2023, world production of ginger was 4.9 million tonnes, led by India with 45% of the total.', image_url = 'https://thumbs.dreamstime.com/z/fresh-sliced-ginger-ingredient-healthy-food-raw-83383735.jpg' WHERE slug = 'ginger';
UPDATE ingredient SET public_summary = 'Cornflour or corn flour may refer to:

Corn starch or cornflour (in the UK), from the endosperm of the kernel of the corn (maize) grain
Maize flour or corn flour (in the US and elsewhere), very finely ground cornmeal, ground from dried maize', image_url = 'https://thumbs.dreamstime.com/b/innovative-cooking-corn-flour-essential-ingredient-modern-recipes-sleek-countertop-backdrop-recipe-making-353887367.jpg' WHERE slug = 'corn-flour';
UPDATE ingredient SET public_summary = 'A yeast is any species of fungus that grows primarily in a unicellular form and reproduces via budding or fission. Yeasts are eukaryotic microorganisms that originated hundreds of millions of years ago, with at least 1,500 species currently recognized. They constitute about 1% of all described fungal species.
Some yeast species have the ability to develop multicellular characteristics by forming strings of connected budding cells known as pseudohyphae or false hyphae or in some cases true hyphae, or quickly evolve into a multicellular cluster with specialised cell organelle functions. Yeast sizes vary greatly, depending on species and environment, typically measuring 3–4 μm in diameter, although some yeasts can grow to 40 μm in size. Most yeasts reproduce asexually by mitosis, and many do so by the asymmetric division process known as budding. With their single-celled growth habit, yeasts can be contrasted with molds, which grow hyphae. Fungal species that can take both forms (depending on temperature or other conditions) are called dimorphic fungi.
The yeast species Saccharomyces cerevisiae converts carbohydrates to carbon dioxide and alcohols through the process of fermentation. The products of this reaction have been used in baking and the production of alcoholic beverages for thousands of years. S. cerevisiae is also an important model organism in modern cell biology research, and is one of the most thoroughly studied eukaryotic microorganisms. Researchers have cultured it in order to understand the biology of the eukaryotic cell and ultimately human biology in great detail. Other species of yeasts, such as Candida albicans, are opportunistic pathogens and can cause infections in humans. Yeasts have recently been used to generate electricity in microbial fuel cells and to produce ethanol for the biofuel industry.
Yeasts do not form a single taxonomic or phylogenetic grouping. The term "yeast" is often taken as a synonym for Saccharomyces cerevisiae, but the phylogenetic diversity of yeasts is shown by their placement in two separate phyla: the Ascomycota and the Basidiomycota. The budding yeasts, or "true yeasts", are classified in the order Saccharomycetales, within the phylum Ascomycota.', image_url = 'https://www.cooklikeczechs.com/wp-content/uploads/2023/11/yeast-dough-ingredients-720x720.jpg' WHERE slug = 'yeast';
UPDATE ingredient SET public_summary = 'Black salt may refer to:

Kala namak, a type of rock salt, salty and pungent-smelling condiment used in South Asia
Black lava salt, a sea salt blended with activated charcoal', image_url = 'https://cleangreensimple.com/wp-content/uploads/himalayan-black-salt-kala-namak.jpg' WHERE slug = 'black-salt';
UPDATE ingredient SET public_summary = 'The potato () is a starchy tuberous vegetable native to the Americas that is consumed as a staple food in many parts of the world. Potatoes are underground stem tubers of the plant Solanum tuberosum, a perennial in the nightshade family Solanaceae.
Wild potato species can be found from the southern United States to southern Chile. Genetic studies show that the cultivated potato has a single origin, in the area of present-day southern Peru and extreme northwestern Bolivia. Potatoes were domesticated there about 7,000–10,000 years ago from a species in the S. brevicaule complex. Many varieties of the potato are cultivated in the Andes region of South America, where the species is indigenous.
The Spanish introduced potatoes to Europe in the second half of the 16th century from the Americas. They are a staple food in many parts of the world and an integral part of much of the world''s food supply. Following centuries of selective breeding, there are now over 5,000 different varieties of potatoes. The potato remains an essential crop in Europe, especially Northern and Eastern Europe, where per capita production is still the highest in the world, while the most rapid expansion in production during the 21st century was in southern and eastern Asia, with China and India leading the world production as of 2023.
Like the tomato and the nightshades, the potato is in the genus Solanum. The aerial parts of the potato contain the toxin solanine. Normal potato tubers that have been grown and stored properly produce glycoalkaloids in negligible amounts, but if sprouts and potato skins are exposed to light, tubers can become toxic.', image_url = 'https://www.lavenderandmacarons.com/wp-content/uploads/2022/08/mediterranean-style-potatoes-ingredients-1024x1536.jpg' WHERE slug = 'potato';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/13fet1006marketsurveyonfoodadditives-181212135819/85/Market-Survey-on-Food-Additives-Anas-Shaikh-13FET1006-8-320.jpg' WHERE slug = 'raising-agents-500-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.openfoodfacts.org/images/products/002/460/001/0030/packaging_en.17.full.jpg' WHERE slug = 'lodised-salt';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://doggonebaking.com/wp-content/uploads/2025/11/Invert_Pin1.jpg' WHERE slug = 'invert-syrup';
UPDATE ingredient SET public_summary = 'Cocoa powder, often simply cocoa, is an aromatic powder derived from the seeds of the Theobroma cacao tree. It is produced by roasting and grinding the seeds, referred to as cocoa beans, and then removing most of the cocoa butter from the resulting paste. Usually sold as a fine powder, cocoa is widely used in baking and beverages, notably hot cocoa, because of its intense chocolate flavor without most of the fat found in cocoa beans. The two main types are natural cocoa powder and Dutch-processed cocoa powder, both of which are available in various fat percentages.
The (non-fat) cocoa solids that make up most of cocoa powder consist primarily of carbohydrates, dietary fiber and protein. They also contain significant amounts of minerals such as iron and magnesium. In addition, cocoa is rich in polyphenols, particularly flavonoids. High-fat cocoa powder is also naturally calorie-dense.', image_url = 'https://i.pinimg.com/originals/00/4c/0e/004c0e1099458e293af59123691fba52.png' WHERE slug = 'cocoa-powder';
UPDATE ingredient SET public_summary = 'Cumin ( ,  ; US also  ; Cuminum cyminum) is a flowering plant in the family Apiaceae, native to the Irano-Turanian Region. Its seeds – each one contained within a fruit, which is dried – are used in the cuisines of many cultures in both whole and ground form. Although cumin is used in traditional medicine, there is no high-quality evidence that it is safe or effective as a therapeutic agent.', image_url = 'https://www.chowhound.com/img/gallery/everything-you-need-to-know-about-cooking-with-cumin/l-intro-1718807966.jpg' WHERE slug = 'cumin';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.orderbtw.com/cdn/shop/files/attapattipremiuming200g_1445x.jpg?v=1759146515' WHERE slug = 'raising-agents-503-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.openfoodfacts.org/images/products/002/460/001/0030/packaging_en.17.full.jpg' WHERE slug = 'lodized-salt';
UPDATE ingredient SET public_summary = 'Black pepper (Piper nigrum) is a flowering vine in the family Piperaceae, cultivated for its fruit (the peppercorn), which is usually dried and used as a spice and seasoning. The fruit is a drupe (stonefruit) which is about 5 mm (1⁄4 in) in diameter (fresh and fully mature), dark red, and contains a stone which encloses a single pepper seed. Peppercorns and the ground pepper derived from them may be described simply as pepper, or more precisely as black pepper (cooked and dried unripe fruit), green pepper (dried unripe fruit), or white pepper (ripe fruit seeds).
Black pepper is native to South Asia. Ground, dried, and cooked peppercorns have been used since antiquity, both for flavour and as a traditional medicine. Black pepper is one of the most commonly traded spices in the world. Its spiciness is due to the chemical compound piperine, which is a different kind of spiciness from that of capsaicin characteristic of chilli peppers. It is ubiquitous in the Western world as a seasoning and is often paired with salt and available on dining tables in shakers or mills.', image_url = 'https://easyandhealthyrecipes.com/images/3s/2022/12/h1-2-scaled.jpg' WHERE slug = 'black-pepper';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.cnadditives.com/uploads/31598/pgpr-e476-food-emulsifier-applications13e02.jpg' WHERE slug = 'emulsifiers-442-476';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://sc04.alicdn.com/kf/A2e7fe3c76c46414d9d56a321fe702705o/271957083/A2e7fe3c76c46414d9d56a321fe702705o.jpg' WHERE slug = 'refined-palmolein-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/foodadditive-180427135442/75/Food-Additive-12-2048.jpg' WHERE slug = 'anticaking-agent-ins-551';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://static.vecteezy.com/system/resources/previews/066/221/951/large_2x/various-types-of-spices-and-condiments-in-bowls-photo.jpeg' WHERE slug = 'spices-and-condiments';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://khni.kerry.com/wp-content/uploads/2017/06/Natural-flavors-image-1024x682.jpg' WHERE slug = 'flavours-natural';
UPDATE ingredient SET public_summary = 'Palm oil is an edible vegetable oil derived from the reddish mesocarp (pulp) of the fruit of the African oil palm. The oil is used in food manufacturing, in beauty products, and as biofuel. Palm oil accounted for about 36% of global oils produced from oil crops in 2017. Palm oils are easier to stabilize and maintain quality of flavor and consistency in ultra-processed foods, so they are frequently favored by food manufacturers.  Globally, humans consumed an average of 7.7 kg (17 lb) of palm oil per person in 2015. Demand has also increased for other uses, such as cosmetics and biofuels, encouraging the growth of palm oil plantations in tropical countries.
The mass production of palm oil in the tropics is a topic for substantial concern for environmental and human rights groups. The palm oil industry is a significant contributor to deforestation in the tropics where palms are grown and has been cited as a factor in social problems due to allegations of human rights violations among growers.
In 2018, a report by the International Union for Conservation of Nature acknowledged that palm oil is much more efficient than other oils in terms of land and water usage; however, deforestation causes more biodiversity loss than switching to other oils. The biggest global producers of palm oil are Indonesia, which produced 60% of it in 2022, followed by Malaysia, Thailand, and Nigeria. Indonesia produces biodiesel primarily from palm oil.', image_url = 'https://heartandsoil.co/wp-content/uploads/2025/03/PalmOil-Chart1-776x1024.png' WHERE slug = 'palm-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://snapcalorie-webflow-website.s3.us-east-2.amazonaws.com/media/food_pics_v2/vegetable_oil.jpg' WHERE slug = 'edible-vegetable-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'hydrogenated-vegetable-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thumbs.dreamstime.com/z/cocoa-ingredients-cocoa-beans-fresh-cocoa-pod-cocoa-mass-isolated-white-background-generative-ai-cocoa-ingredients-284260116.jpg' WHERE slug = 'cocoa-mass';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/I/51Hv5xUb68L._SL1000_.jpg' WHERE slug = 'artificial-flavouring-substances-vanilla-cake';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.chibiotech.com/wp-content/uploads/2026/03/1-Inverted-Sugar-Syrup-CHIBIO-600x600.webp' WHERE slug = 'invert-sugar';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.openfoodfacts.org/images/products/007/874/208/4169/ingredients_en.4.full.jpg' WHERE slug = 'carbonated-water';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://factsscan.com/wp-content/uploads/2026/06/What-Is-an-Acidity-Regulator.webp' WHERE slug = 'acidity-regulator-330';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://c8.alamy.com/comp/3CR67PG/e211-sodium-benzoate-molecule-food-additive-food-preservative-against-bacteria-molds-and-yeasts-vector-illustration-3CR67PG.jpg' WHERE slug = 'preservative-ins-211';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://myfloura.com/blog/wp-content/uploads/2023/03/Images-for-Floura-BLOG-3.jpg' WHERE slug = 'refined-wheat-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://tiimg.tistatic.com/fp/1/007/535/100-pure-and-natural-unrefined-palm-edible-oil-for-cooking-food-804.jpg' WHERE slug = 'edible-vegetable-oil-palm-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://static.vecteezy.com/system/resources/previews/071/586/930/large_2x/fresh-onions-and-dehydrated-onion-powder-create-a-versatile-culinary-ingredient-for-cooking-photo.jpg' WHERE slug = 'onion-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image4.slideserve.com/9072802/types-of-raising-agent-l.jpg' WHERE slug = 'raising-agent-ins-500-ii';
UPDATE ingredient SET public_summary = 'Garlic powder is a spice that is derived from dehydrated garlic and used in cooking for flavor enhancement. The process of making garlic powder includes drying and dehydrating the vegetable, then powdering it through machinery or home-based appliances depending on the scale of production. Garlic powder is a common component of spice mix. It is also a common component of seasoned salt.', image_url = 'https://www.marthastewart.com/thmb/0IJ204h9eWw-EVfdCYcNYBTnQyc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/power-of-garlic-powder-getty-1023-4b070d93e22b4765be0f18995d55723e.jpg' WHERE slug = 'garlic-powder';
UPDATE ingredient SET public_summary = 'Baking powder is a dry chemical leavening agent, a mixture of a carbonate or bicarbonate and a weak acid. The base and acid are prevented from reacting prematurely by the inclusion of a desiccant such as cornstarch. Baking powder is used to increase the volume and lighten the texture of baked goods. It works by releasing carbon dioxide gas into a batter or dough through an acid–base reaction, causing bubbles in the wet mixture to expand and thus leavening the mixture.  
The first commercially sold baking powder ever was Borwick''s Baking Powder, launched in England in 1842 by George Borwick, who had spent eleven years from 1831 perfecting a formula passed to him by his father-in-law, a chemist, as a yeast substitute for home baking. The following year, in 1843, pharmacist Alfred Bird developed his own single-acting baking powder (meaning that it releases all of its carbon dioxide as soon as it is dampened). In 1856, Eben Norton Horsford, the Rumford Professor at Harvard University, received an American patent, for monocalcium phosphate, for baking powder. In the 1860s, Horsford developed the first double-acting baking powder, which releases some carbon dioxide when dampened and later releases more of the gas when heated by baking
Baking powder is used instead of yeast for end-products where fermentation flavors would be undesirable,  
or where the batter lacks the elastic structure to hold gas bubbles for more than a few minutes, and to speed the production of baked goods. Because carbon dioxide is released at a faster rate through the acid–base reaction than through fermentation, breads made by chemical leavening are called quick breads.  The introduction of baking powder was revolutionary in minimizing the time and labor required to make breadstuffs. It led to the creation of new types of cakes, cookies, biscuits, and other baked goods.', image_url = 'https://images.openfoodfacts.org/images/products/001/990/000/3202/ingredients_en.3.full.jpg' WHERE slug = 'baking-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.ragus.co.uk/wp-content/uploads/2018/09/Refined_vs_Natural_Sugars_01_ss_2191871297_1295x715px.jpg' WHERE slug = 'refined-sugar';
UPDATE ingredient SET public_summary = 'Wheat flour is a powder made from the grinding of common wheat used for human consumption. Wheat varieties are called "soft" or "weak" if gluten content is low, and are called "hard" or "strong" if they have high gluten content. Hard flour, or bread flour, is high in gluten, with 12% to 14% gluten content, and its dough has elastic toughness that holds its shape well once baked. Soft flour is comparatively low in gluten and thus results in a loaf with a finer, crumbly texture. Soft flour, in the US, is usually divided into cake flour, which is the lowest in gluten, and pastry flour, which has slightly more gluten than cake flour.
In terms of the parts of the grain (the grass fruit) used in flour—the endosperm or protein/starchy part, the germ or protein/fat/vitamin-rich part, and the bran or fiber part—there are three general types of flour. White flour is made from the endosperm only. Brown flour includes some of the grain''s germ and bran, while whole grain or wholemeal flour is made from the entire grain, including the bran, endosperm, and germ. Germ flour is made from the endosperm and germ, excluding the bran.', image_url = 'https://img.freepik.com/premium-photo/flour-delicious-food-ingredients-healthy-wheat_1015293-45799.jpg' WHERE slug = 'wheat-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://static.vecteezy.com/system/resources/previews/053/427/784/large_2x/the-ingredients-of-milk-and-other-dairy-products-photo.jpeg' WHERE slug = 'milk';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://peaksupps.co.uk/cdn/shop/files/Skimmed_Milk_powder_-_500g.png?v=1771591081' WHERE slug = 'skimmed-milk-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://tiimg.tistatic.com/fp/1/007/535/100-pure-and-natural-unrefined-palm-edible-oil-for-cooking-food-804.jpg' WHERE slug = 'edible-vegetable-oil-palm';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00AnGoJydPNwku/Food-Additive-E471-Emulsifier-High-Iodine-Value-Gms-Glycerol-Monostearate.jpg' WHERE slug = 'emulsifier-ins-471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.sugarsaltmagic.com/wp-content/uploads/2023/04/Fajita-Seasoning-6FEAT-680x860.jpg' WHERE slug = 'seasoning-sugar';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://rukminim2.flixcart.com/image/960/1280/xif0q/baking-ingredient/p/n/x/250-soy-lecithin-powder-e322-250g-soya-lecithin-emulsifier-original-imahgfxfhwjyqrue.jpeg?q=60' WHERE slug = 'emulsifier-322-i';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/rice-bran-oil-glass-with-seed-rice-white-backgroundorganic-vegetable-oil-pure-homemade-processedraw-food-ingredient-cooking-natural-good-healthlow-calories-antioxidant_301927-695.jpg?w=2000' WHERE slug = 'rice-bran-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.mycolombianrecipes.com/wp-content/uploads/2015/06/soy-bean-oil-campaign.jpg' WHERE slug = 'refined-soyabean-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodrealitycheck.com/wp-content/uploads/2025/12/e471-2048x1536.jpg' WHERE slug = 'emulsifiers-471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://www.lilsipper.com/wp-content/uploads/2018/04/2BA8B644-0B2E-474D-B215-F35A29D1EE05.jpg' WHERE slug = 'citric-acid';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.foodingredientfacts.org/wp-content/uploads/2016/02/AdobeStock_87648286.jpeg' WHERE slug = 'spices';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.stanfordchem.com/wp-content/uploads/2026/01/Antioxidant-Rich-Foods.png' WHERE slug = 'antioxidant-ins-300';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://as1.ftcdn.net/jpg/10/87/28/76/1000_F_1087287657_1yySE5qahlgUAwhXiU2jxh1eIWI43eSS.jpg' WHERE slug = 'jaggery';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/spices-condiments-food_231794-1352.jpg' WHERE slug = 'spices-condiments';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.sgr777foods.com/wp-content/uploads/2026/03/Asafoetida-Ingredients-Guide_-Everything-You-Should-Know.webp' WHERE slug = 'asafoetida';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'hydrogenated-vegetable-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.squarespace-cdn.com/content/v1/55196103e4b0dfcc47c597ab/1468610051672-GGI4FLBXMW23J02773AP/image-asset.png?format=1500w' WHERE slug = 'natural-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.theconsciousplantkitchen.com/wp-content/uploads/2019/06/unexpected-sources-of-gluten-1.png' WHERE slug = 'wheat-gluten';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://bionutriciaextract.com/wp-content/uploads/2024/06/HVP-Powder-Paper-Can-200g-01.webp' WHERE slug = 'hydrolysed-vegetable-protein';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://image.shutterstock.com/z/stock-photo-nutrition-facts-of-almonds-with-almonds-background-224458213.jpg' WHERE slug = 'almonds';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://raodoctor.com/wp-content/uploads/2020/07/sunflower-oil-1024x1024.jpg' WHERE slug = 'refined-sunflower-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn0.woolworths.media/content/wowproductimages/large/035176_3.jpg' WHERE slug = 'malt-extract';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00AnGoJydPNwku/Food-Additive-E471-Emulsifier-High-Iodine-Value-Gms-Glycerol-Monostearate.jpg' WHERE slug = 'emulsifier-471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-vector/vitamins-minerals-food-sources-nutrition_8071-47952.jpg?w=2000' WHERE slug = 'vitamins';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://ichef.bbci.co.uk/food/ic/food_16x9_1600/foods/c/coriander_seeds_16x9.jpg' WHERE slug = 'coriander';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/originals/23/e6/cb/23e6cb0f96a5d4b8192586d226ed89a1.jpg' WHERE slug = 'fractionated-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.alcofoods.com/cdn/shop/products/RedChiliPowder03_3_af2287b5-71d8-447c-a986-cc87f06f00c7_1445x.jpg?v=1680847605' WHERE slug = 'red-chilli-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0082/7722/9604/products/10021_glucose_syrup-2.jpg?v=1610469033' WHERE slug = 'glucose-syrup';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://down-ph.img.susercontent.com/file/cn-11134207-7r98o-lw4e7uer91cz83' WHERE slug = 'maltitol';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.easybuyingredients.com/wp-content/uploads/2023/09/What-Makes-Soy-Lecithin-a-Super-Ingredient-for-Food-Technology-A-Deep-Dive-into-Its-Composition-and-Function-1024x788.png' WHERE slug = 'emulsifier-soya-lecithin';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://factsscan.com/wp-content/uploads/2026/06/What-Is-an-Acidity-Regulator.webp' WHERE slug = 'acidity-regulators-ins-330';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://agutsygirl.com/wp-content/uploads/2020/06/Your-Guide-to-Emulsifiers-in-Food-agutsygirl.com-emulsifiers-guthealth-packagedfoods-master-list-683x1024.png' WHERE slug = 'emulsifiers';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.simplyrecipes.com/thmb/vHJ_FaCJLIbwCrXiC7tRg7os8KM=/3900x2600/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Ingredient-Cardamom-LEAD-6-13917b2f558440c8b1ee9b1f4b1bebd4.jpg' WHERE slug = 'cardamom';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://media.sciencephoto.com/image/f0368428/800wm/F0368428-Container_of_the_food_additive_E322.jpg' WHERE slug = 'emulsifier-ins-322';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://tiimg.tistatic.com/fp/1/005/539/double-acting-baking-powder-352.jpg' WHERE slug = 'raising-agents-ins-500-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://bionutriciaextract.com/wp-content/uploads/2024/06/HVP-Powder-Paper-Can-200g-01.webp' WHERE slug = 'hydrolyzed-vegetable-protein';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://factsscan.com/wp-content/uploads/2026/06/Common-Examples-of-Acidity-Regulators.webp' WHERE slug = 'acidity-regulator';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thumbs.dreamstime.com/z/red-chilli-red-chilli-strong-ingredient-vietnamese-cuisine-139199744.jpg' WHERE slug = 'red-chilli';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://reusegrowenjoy.com/wp-content/uploads/Tomato-Powder-Recipe-683x1024.jpg' WHERE slug = 'tomato-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.sgr777foods.com/wp-content/uploads/2025/10/chilli-powder-ingredients-1-1.webp' WHERE slug = 'chilli-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://media.sciencephoto.com/image/f0368428/800wm/F0368428-Container_of_the_food_additive_E322.jpg' WHERE slug = 'emulsifiers-322-i';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'flavour-natural-and-nature-identical-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://2.wlimg.com/product_images/bc-full/2021/6/8119872/palmolein-oil-1624355240-5867868.jpeg' WHERE slug = 'edible-vegetable-oil-palmolein';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://as2.ftcdn.net/jpg/14/42/51/49/1000_F_1442514925_NPzFwqtvnwjmBf0Wgw7XpHSBmZTqwzxj.jpg' WHERE slug = 'corn-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://kalber.exportdepartment.ir/export-brands/uploads/images/emulsifiers- stabilizers.jpg' WHERE slug = 'emulsifier';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'natural-and-nature-identical-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cravinghomecooked.com/wp-content/uploads/2019/06/the-best-chili-recipe-ingredients.jpg' WHERE slug = 'chilli';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.eatingbirdfood.com/wp-content/uploads/2022/09/Chili-Verde-Ingredients-min-1024x1536.jpg' WHERE slug = 'green-chilli';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://testfoodkitchen.com/wp-content/uploads/2025/09/file-8.jpg-8.jpg' WHERE slug = 'humectant-ins-422';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cms-static.wehaacdn.com/hoards-com/images/dairy-foods-web.26772.jpg' WHERE slug = 'milk-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.himalayannatives.com/storage/editor_61f7d0237f358-hn-blog-ghee-dish-1-1.webp' WHERE slug = 'ghee';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/pptft101-210224130014/75/food-ingredients-and-its-type-10-2048.jpg' WHERE slug = 'raising-agents-ins-503-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.tarladalal.com/media/recipe/method/2025/01/16/list-of-ingredients-for-cheese-powder-1-199404.webp' WHERE slug = 'cheese-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://flavorthemoments.com/wp-content/uploads/2024/09/roasted-tomato-soup-recipe-ingredients-labelled.jpg' WHERE slug = 'tomato';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://domerock.org/wp-content/uploads/2025/11/Screenshot-2025-11-17-115553-1024x635.png' WHERE slug = 'palmolein';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'nature-identical';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://rukminim2.flixcart.com/image/960/1280/xif0q/baking-ingredient/p/n/x/250-soy-lecithin-powder-e322-250g-soya-lecithin-emulsifier-original-imahgfxfhwjyqrue.jpeg?q=60' WHERE slug = 'emulsifier-322';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://krichmount.com/wp-content/uploads/2025/09/CUMIN-POWDER3-1.jpg' WHERE slug = 'cumin-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/998e524e-12ce-4904-a70a-4c2f45f49cc0.__CR0,0,970,600_PT0_SX970_V1___.jpg' WHERE slug = 'interesterified-vegetable-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://c8.alamy.com/comp/2Y6GRWF/organic-himalayan-pink-rock-salt-in-spoon-healthy-food-ingredient-2Y6GRWF.jpg' WHERE slug = 'rock-salt';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.gobaledibleoilexporters.com/upload/Refined-Soybean-Oil.webp' WHERE slug = 'refined-soybean-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://static.vecteezy.com/system/resources/previews/013/753/703/large_2x/besan-gram-flour-or-chickpea-flour-is-a-powder-made-from-ground-chickpea-known-as-bengal-gram-free-photo.jpg' WHERE slug = 'gram-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-vector/various-mix-spices-food-ingredients-curry-masala-chilicloves-cinnamon-sticks-white-background_1045923-1492.jpg?w=2000' WHERE slug = 'mixed-spices';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/noodlesproject-160530152234/95/personal-study-of-18-noodle-products-of-7-companies-in-india-29-638.jpg?cb=1465722507' WHERE slug = 'flavour-enhancers-ins-627-ins-631';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://slowthecookdown.com/wp-content/uploads/2020/01/turmeric-recipes-cover.jpg' WHERE slug = 'turmeric';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/flavorenhancers-190310184417/85/Flavor-enhancers-9-320.jpg' WHERE slug = 'flavour-enhancers-627-631';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/I/91l27gjmxVL.jpg' WHERE slug = 'whey-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.squarespace-cdn.com/content/v1/6004b3d3dfad4a36491e9a9f/ea3e8a79-2df4-465c-b4d4-9875bbdb0331/8.png' WHERE slug = 'vitamin-c';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.sharmispassions.com/wp-content/uploads/2022/01/curry-leaves-powder-ingredients1-683x1024.jpg' WHERE slug = 'curry-leaves';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.cheflorarecipes.com/wp-content/uploads/2026/03/Asian-Honey-Protocol-Recipe-2-768x1024.png' WHERE slug = 'honey';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/originals/17/eb/af/17ebaf09e2a6d492610eb3f6f8bd0f19.png' WHERE slug = 'minerals';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2022/09/27/0/FNK_Homemade-Tomato-Paste_H_s4x3.jpg.rend.hgtvcom.616.462.suffix/1664309746356.webp' WHERE slug = 'tomato-paste';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://5.imimg.com/data5/SELLER/Default/2026/4/602876387/IN/HU/MF/236/e551-anti-caking-agent-for-food-500x500.png' WHERE slug = 'anticaking-agent-551';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://gs-blog-content.s3.amazonaws.com/recipe/coconut-oil/coconut-oil-in-recipes/image.png' WHERE slug = 'coconut-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://www.nutrientsreview.com/wp-content/uploads/2014/09/Foods-High-in-Fructooligosaccharides-FOS.jpg' WHERE slug = 'oligofructose';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/besan-gram-chickpea-flour-is-pulse-flour-made-from-variety-ground-chickpea-known-as-bengal-gram-popular-ingredient-pakora-pakoda-bajji-snack_466689-29670.jpg?w=740' WHERE slug = 'bengal-gram-flour-besan';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.tastingtable.com/img/gallery/22-sweet-ingredients-you-should-always-keep-in-your-pantry/cinnamon-1696267099.jpg' WHERE slug = 'cinnamon';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://sc01.alicdn.com/kf/H42e963b5c8da4620bea294824c4547510.png' WHERE slug = 'refined-palmolein';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://aksaltsuppliers.in/assets/edible_salt_1766563729306-DwAPX2tZ.png' WHERE slug = 'edible-salt';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://s3.amazonaws.com/ossleads-bucket/plezi-production/documents/files/614b/a0fd/5406/7a73/4358/a889/original/Chef_Landing_Page_-_yeast_benefits_web_2_-_resized.png?1632346364' WHERE slug = 'yeast-extract';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00KfZkceAqEDuT/Food-Additive-Caramel-Powder-CAS-8028-89-5-Pigment-Caramel-Color-E150A-E150c-E150d.jpg' WHERE slug = 'colour-150d';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.natureword.com/wp-content/uploads/2014/10/Nutritional-Facts-Peanuts.jpg' WHERE slug = 'peanuts';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/wahid-foodpackaging-190424171341/75/Food-Packaging-15-2048.jpg' WHERE slug = 'stabilizers-ins-407';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://virtualinternational.in/wp-content/uploads/2025/09/Rice-Bran-Oil-1024x987.png' WHERE slug = 'edible-vegetable-oil-rice-bran-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://s.alicdn.com/@sc02/kf/A5fef4e5f85b44d13b2313356313847d8Z.jpg' WHERE slug = 'edible-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/f4151d61-315a-46d6-9a6c-befbd60a89d1.__CR0,0,970,600_PT0_SX970_V1___.png' WHERE slug = 'dough-conditioner-223';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/13fet1006marketsurveyonfoodadditives-181212135819/85/Market-Survey-on-Food-Additives-Anas-Shaikh-13FET1006-8-320.jpg' WHERE slug = 'leavening-agents-ins-500-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.openfoodfacts.org/images/products/408/860/009/9071/nutrition_en.37.full.jpg' WHERE slug = 'lemon-juice';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/736x/fc/c6/0a/fcc60a5ffe9f7dfec3a67d64406e1a74.jpg' WHERE slug = 'lactose';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.spoonforkbacon.com/wp-content/uploads/2023/05/fried_rice_ingredients.jpg' WHERE slug = 'rice';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://testfoodkitchen.com/wp-content/uploads/2025/09/file-8.jpg-8.jpg' WHERE slug = 'humectant-422';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.culinaryhill.com/wp-content/uploads/2021/08/How-to-Make-Mustard-Ingredients-Culinary-Hill-568x378.jpg' WHERE slug = 'mustard';