UPDATE ingredient SET public_summary = 'Ebenezer Harold Fuller "Ginger" Owers (21 October 1888 – June 1951) was an English footballer who played as a centre forward. He made over 90 appearances in the Football League and over 30 appearances in the Scottish League in the years prior to the First World War.', image_url = 'https://foodpowderindia.com/wp-content/uploads/2024/06/ginger1.jpg' WHERE slug = 'ginger-powder';
UPDATE ingredient SET public_summary = 'Cloves are the aromatic flower buds of a tree in the family Myrtaceae, Syzygium aromaticum (). They are native to the Maluku Islands, or Moluccas, in Indonesia, and are commonly used as a spice, flavoring, or fragrance in consumer products, such as toothpaste, soaps, or cosmetics. Freshly harvested cloves are available throughout the year owing to different harvest seasons across various countries.', image_url = 'https://boreddaddy.com/wp-content/uploads/2025/07/66ff0566b3eef39b517ad7b5_66aa859.webp' WHERE slug = 'clove';
UPDATE ingredient SET public_summary = 'A raisin is a dried grape. Raisins are produced in many regions of the world and may be eaten raw or used in cooking, baking, and brewing. The word raisin is commonly used for the dried dark-colored seedless grape, while sultana is a golden-colored dried grape, and currant is a dried small Black Corinth seedless grape.', image_url = 'https://thecoconutmama.com/wp-content/uploads/2024/03/shutterstock_280639877-scaled.jpg' WHERE slug = 'raisins';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thumbs.dreamstime.com/b/composition-raw-chicken-meat-ingredients-cooking-188773178.jpg' WHERE slug = 'chicken-meat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.squarespace-cdn.com/content/v1/5ae2b8fdf93fd4d57303a71d/ed82a902-4fb0-434f-b946-7fa0b6a1b2af/Baking-powders.jpg' WHERE slug = 'raising-agents';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/13fet1006marketsurveyonfoodadditives-181212135819/85/Market-Survey-on-Food-Additives-Anas-Shaikh-13FET1006-8-320.jpg' WHERE slug = 'raising-agent-500-ii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.easybuyingredients.com/wp-content/uploads/2023/09/What-Makes-Soy-Lecithin-a-Super-Ingredient-for-Food-Technology-A-Deep-Dive-into-Its-Composition-and-Function-1024x788.png' WHERE slug = 'emulsifier-soy-lecithin';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://get.pxhere.com/photo/food-cashew-nut-ingredient-nuts-seeds-cuisine-Cashew-family-plant-produce-mixed-nuts-dish-peanut-superfood-legume-1627044.jpg' WHERE slug = 'cashew-nuts';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://c8.alamy.com/comp/3CR67PG/e211-sodium-benzoate-molecule-food-additive-food-preservative-against-bacteria-molds-and-yeasts-vector-illustration-3CR67PG.jpg' WHERE slug = 'preservative-211';
UPDATE ingredient SET public_summary = 'Wheat Fields is a series of dozens of paintings by Dutch Post-Impressionist artist Vincent van Gogh, products of his religious studies and sermons, connection to nature, appreciation of manual laborers and desire to provide a means of offering comfort to others.  The wheat field works demonstrate his progression as an artist from Wheat Sheaves made in 1885 in the Netherlands to the colorful and dramatic 1888–1890 paintings from Arles, Saint-Rémy and Auvers-sur-Oise in rural France.', image_url = 'https://nuffoodsspectrum.in/wp-content/uploads/2026/03/Wheat-bran_-future-of-functional-foods.png' WHERE slug = 'wheat-fibre';
UPDATE ingredient SET public_summary = 'Cabbage, comprising several cultivars of Brassica oleracea, is a leafy green, red (purple), or white (pale green) biennial plant grown as an annual vegetable crop for its dense-leaved heads. It is descended from the wild cabbage (B. oleracea var. oleracea), and belongs to the "cole crops" or brassicas, meaning it is closely related to broccoli and cauliflower (var. botrytis); Brussels sprouts (var. gemmifera); and Savoy cabbage (var. sabauda).
A cabbage generally weighs between 500 and 1,000 grams (1 and 2 lb). Smooth-leafed, firm-headed green cabbages are the most common, with smooth-leafed purple cabbages and crinkle-leafed savoy cabbages of both colours being rarer. Under conditions of long sunny days, such as those found at high northern latitudes in summer, cabbages can grow quite large. As of 2012, the heaviest cabbage was 62.71 kilograms (138 lb 4 oz).  Cabbage heads are generally picked during the first year of the plant''s life cycle, but plants intended for seed are allowed to grow a second year and must be kept separate from other cole crops to prevent cross-pollination. Cabbage is prone to several nutrient deficiencies, as well as to multiple pests, and bacterial and fungal diseases.
Cabbage was most likely domesticated somewhere in Europe in ancient history before 1000 BC. Cabbage use in cuisine has been documented since antiquity. It was described as a table luxury in the Roman Empire. By the Middle Ages, cabbage had become a prominent part of European cuisine, as indicated by manuscript illuminations. New variants were introduced from the Renaissance on, mostly by Germanic-speaking peoples. Savoy cabbage was developed in the 16th century. By the 17th and 18th centuries, cabbage was popularised as a staple food in central, northern, and Eastern Europe. It was also employed by European sailors to prevent scurvy during long sea voyages. Starting in the early modern era, cabbage was exported to the Americas, Asia, and around the world.
Cabbages can be prepared many different ways for eating; they can be pickled, fermented (for dishes such as sauerkraut and kimchi), steamed, stewed, roasted, sautéed, braised, or eaten raw. Raw cabbage is a rich source of vitamin K, vitamin C, and dietary fiber. China is the largest producer of cabbages, providing 48% of the world total.', image_url = 'https://loveincrediblerecipes.com/wp-content/uploads/2025/05/cabbage-curry-ingredients.jpg' WHERE slug = 'cabbage';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://imgv2-1-f.scribdassets.com/img/document/12726785/original/565312a3d2/1?v=1' WHERE slug = 'emulsifiers-472e';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0735/9163/products/EDEXFC_BlackPepperPowder_700x700.png?v=1669367076' WHERE slug = 'black-pepper-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://5.imimg.com/data5/ANDROID/Default/2025/7/529414511/IY/GA/WL/1947391/product-jpeg-500x500.jpg' WHERE slug = 'emulsifier-of-vegetable-origin-472e';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/blogs/2147508904/images/54a871d-4f4e-5ec-bd63-fa601456d1f_natural_vs_non_natural_6.png' WHERE slug = 'natural-flavours-and-natural-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://factsscan.com/wp-content/uploads/2026/06/What-Is-an-Acidity-Regulator.webp' WHERE slug = 'acidity-regulator-ins-260';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.stanfordchem.com/wp-content/uploads/2026/01/Antioxidant-Rich-Foods.png' WHERE slug = 'antioxidant-300';
UPDATE ingredient SET public_summary = 'An egg is an organic vessel grown by an animal to carry a possibly fertilized egg cell – a zygote. Within the vessel, an embryo is incubated until it has developed enough to survive on its own, at which point the animal hatches. Reproductive structures similar to the egg in other kingdoms are termed "spores", or in spermatophytes "seeds", or in gametophytes "egg cells".
Most arthropods, vertebrates (excluding live-bearing mammals), and mollusks lay eggs, although some, such as scorpions, do not. Reptile eggs, bird eggs, and monotreme eggs are laid out of water and are surrounded by a protective shell, either flexible or inflexible. Eggs laid on land or in nests are usually kept within a warm and favorable temperature range while the embryo grows. When the embryo is adequately developed it hatches; i.e., breaks out of the egg''s shell. Some embryos have a temporary egg tooth they use to crack, pip, or break the eggshell or covering.
For people, eggs are a popular food item, and they appear on menus worldwide. Eggs remain an important symbol in folklore and mythology, symbolizing life, healing, and rebirth. They are frequently the subject of decoration. Egg collecting has been popular in some cultures, although the practice is now banned in many jurisdictions. Chicken eggs are used in the production of vaccines for infectious diseases.', image_url = 'https://www.cookingwithnanaling.com/wp-content/uploads/2023/11/devilled-eggs-ingredients.jpg' WHERE slug = 'egg';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.cookingwithnanaling.com/wp-content/uploads/2023/11/devilled-eggs-ingredients.jpg' WHERE slug = 'eggs';
UPDATE ingredient SET public_summary = 'And Starring Pancho Villa as Himself is a 2003 American Western biographical drama television film directed by Bruce Beresford, written by Larry Gelbart, and starring Antonio Banderas as Pancho Villa. The cast also includes Alan Arkin, Jim Broadbent, Michael McKean, Eion Bailey, and Alexa Davalos. It premiered on HBO on September 7, 2003.
Executive producer Joshua D. Maurer, who originally conceived the story and did extensive research, sold the project to HBO and then brought on executive producer Mark Gordon and hired Gelbart to write the screenplay. At the time of production, this was the most expensive 2-hour television/cable film ever made, with a budget of over $30 million. It was shot almost entirely on location in and around San Miguel de Allende, Mexico.', image_url = 'https://static.wixstatic.com/media/9325ae_75229c5e07f145429c6a7f541050d6c3~mv2.png/v1/fill/w_440,h_536,al_c,q_85,enc_avif,quality_auto/9325ae_75229c5e07f145429c6a7f541050d6c3~mv2.png' WHERE slug = 'and-sugar';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://tiimg.tistatic.com/fp/1/007/535/100-pure-and-natural-unrefined-palm-edible-oil-for-cooking-food-804.jpg' WHERE slug = 'edible-vegetable-oil-palmolein-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/marketsurvey-150420020010-conversion-gate02/85/Analysis-of-Market-survey-13-320.jpg' WHERE slug = 'stabilizers-ins-466';
UPDATE ingredient SET public_summary = 'Mace may refer to:', image_url = 'https://s.alicdn.com/@sc02/kf/Aeabf88abab464a92b477c02b4154ab39v.jpg' WHERE slug = 'mace';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://mtroyal.com.tr/en/wp-content/uploads/2025/01/Desiccated-Coconut.jpg' WHERE slug = 'desiccated-coconut';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image1.slideserve.com/1928985/leavening-agents2-l.jpg' WHERE slug = 'leavening-agents-ins-503-ii';
UPDATE ingredient SET public_summary = 'Soy sauce (sometimes called soya sauce in British English) is a liquid condiment of Chinese origin, traditionally made from a fermented paste of soybeans, roasted grain, brine, and Aspergillus oryzae or Aspergillus sojae molds (kōji). It is recognized for its saltiness and pronounced umami taste.
Soy sauce was created in its current form about 2,200 years ago during the Western Han dynasty of ancient China. Since then, it has become an important ingredient in East and Southeast Asian cooking as well as a condiment worldwide.', image_url = 'https://cookingformysoul.com/wp-content/uploads/2026/04/ingredients-soy-sauce-chicken-min-1024x1536.jpg' WHERE slug = 'soy-sauce';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://galaxyflavours.com/cdn/shop/files/malted-milk-food-flavouring-1-litre_1445x.png?v=1777104346' WHERE slug = 'artificial-flavouring-substances-milk';
UPDATE ingredient SET public_summary = 'Condensed milk is cow''s milk from which water has been removed (roughly 60% of it). It is most often found with sugar added, in the form of sweetened condensed milk, to the extent that the terms "condensed milk" and "sweetened condensed milk" are often used interchangeably today. Sweetened condensed milk is a very thick, sweet product, which when canned can last for years without refrigeration if not opened. The product is used in numerous dessert dishes in many countries.
A related product is evaporated milk, which has undergone a lengthier preservation process because it is not sweetened.', image_url = 'https://images.openfoodfacts.org/images/products/408/860/015/5791/ingredients_en.12.full.jpg' WHERE slug = 'condensed-milk';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://vasafoods.com/wp-content/uploads/2023/10/vasaoil-1024x1024.jpg' WHERE slug = 'refined-vegetable-oil';
UPDATE ingredient SET public_summary = 'Susan Jane Powter (born December 22, 1957) is an Australian-born American motivational speaker, nutritionist, personal trainer, and author, who rose to fame in the 1990s with her catchphrase "Stop the Insanity!", the centerpiece of her weight-loss infomercial. Powter has been described as a cross between Richard Simmons and Betty Friedan and "the Lenny Bruce of Wellness".
An advocate of a whole-foods, organic, low-fat diet, and regular cardiovascular and strength-training exercise, Powter also has condemned the diet industry. Her platinum-white close-cropped haircut, emphatic speaking manner, and habit of being barefoot while speaking in public, became trademarks of her celebrity.', image_url = 'https://onehotoven.com/wp-content/uploads/2024/06/powdered-sugar-labeled-1.jpg' WHERE slug = 'sugar-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00KfZkceAqEDuT/Food-Additive-Caramel-Powder-CAS-8028-89-5-Pigment-Caramel-Color-E150A-E150c-E150d.jpg' WHERE slug = 'colour-ins-150d';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'hydrogenated-oils';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://marshalfoods.co/wp-content/uploads/2024/08/Pink-salt-box.png' WHERE slug = 'himalayan-pink-salt';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://media-cdn2.greatbritishchefs.com/media/q2ohba2i/img26854.jpg' WHERE slug = 'star-anise';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://factsscan.com/wp-content/uploads/2026/06/Common-Examples-of-Acidity-Regulators.webp' WHERE slug = 'acidity-regulators-330';
UPDATE ingredient SET public_summary = 'The almond (Prunus amygdalus, syn. Prunus dulcis (Mill.) D.A.Webb, nom. illeg. non Prunus dulcis Rouchy) is a species of tree from the genus Prunus. Along with the peach, it is classified in the subgenus Amygdalus, distinguished from the other subgenera by corrugations on the woody shell (endocarp) surrounding the seed.
The fruit of the almond is a drupe, consisting of an outer hull and a hard shell with the seed, which is not a true nut. Shelling almonds refers to removing the shell to reveal the seed. Almonds are sold shelled or unshelled. Blanched almonds are unshelled almonds that have been treated with hot water to soften the outer skin, which is then removed to reveal the white embryo. Once almonds are cleaned and processed, they can be stored for around a year if kept refrigerated; at higher temperatures they will become rancid more quickly. Almonds are used in many cuisines, often featuring prominently in desserts, such as marzipan.
The almond tree prospers in a moderate Mediterranean climate with cool winter weather. It is rarely found wild in its original setting. Almonds were one of the earliest domesticated fruit trees, due to the ability to produce quality offspring entirely from seed, without using suckers and cuttings. Evidence of domesticated almonds in the Early Bronze Age has been found in the archeological sites of the Middle East, and subsequently across the Mediterranean region and similar arid climates with cool winters.
California produces about 80% of the world''s almond supply. Due to high acreage and water demand for almond cultivation, and need for pesticides, California almond production may be unsustainable, especially during the persistent drought and heat from climate change in the 21st century. Droughts in California have caused some producers to leave the industry, leading to lower supply and increased prices.', image_url = 'https://www.soulfullymade.com/wp-content/uploads/2025/03/honey-roasted-almonds-ingredients-labeled-1024x1536.jpg' WHERE slug = 'almond';
UPDATE ingredient SET public_summary = 'The hazelnut is the fruit of the hazel tree and therefore includes any of the nuts deriving from species of the genus Corylus, especially the nuts of the species Corylus avellana. They are also known as cobnuts or filberts according to species.
Hazelnuts are used as a snack food, in baking and desserts, and in breakfast cereals such as muesli. In confectionery, they are used to make praline, and also used in combination with chocolate for chocolate truffles and products such as chocolate bars and hazelnut cocoa spreads such as Nutella. They are also used in Frangelico liqueur. Hazelnut oil, pressed from hazelnuts, is strongly flavored and high in monounsaturated fat. It is used as a cooking oil and as a salad or vegetable dressing.
In 2023, Turkey was the world''s largest producer of hazelnuts, accounting for 57.7% of total production.', image_url = 'https://www.herbazest.com/imgs/0/3/8/760502/hazelnut-nutrition-962191-section.png' WHERE slug = 'hazelnuts';
UPDATE ingredient SET public_summary = 'Cottonseed oil is cooking oil from the seeds of cotton plants of various species, mainly Gossypium hirsutum and Gossypium herbaceum, that are grown for cotton fiber, animal feed, and oil.
Cotton seed has a similar structure to other oilseeds, such as sunflower seed, having an oil-bearing kernel surrounded by a hard outer hull; in processing, the oil is extracted from the kernel. Cottonseed oil is used for salad oil, mayonnaise, salad dressing, and similar products because of its flavor stability.', image_url = 'https://foodstruct.com/foodinfographic/en_cottonseed-oil.jpg.webp' WHERE slug = 'cotton-seed-oil';
UPDATE ingredient SET public_summary = 'Cocoa solids may refer to:

Total cocoa solids, the sum of all components derived from the cocoa bean
Non-fat cocoa solids, the cocoa components remaining after the cocoa butter has been removed, primarily found in defatted cocoa powder
Chocolate liquor (or cocoa mass), the ground paste made from cocoa beans, containing both non-fat cocoa solids and cocoa butter in roughly equal proportions', image_url = 'https://foodstruct.com/compareimages/cocoa-drypowder-unsweetened-vs-spread-nutrition.jpg' WHERE slug = 'cocoa-solids-2';
UPDATE ingredient SET public_summary = 'Chocolate is a food made from roasted and ground cocoa beans. It can be a liquid, solid, or paste. It is eaten on its own and used to flavor other foods. 
Cocoa beans are the processed seeds of the cacao tree (Theobroma cacao). They are usually fermented to develop the flavor, then dried, cleaned, and roasted. The shell is removed to reveal nibs, which are ground to chocolate liquor (unadulterated chocolate in rough form.) The liquor can be further processed into cocoa butter and cocoa powder, or shaped and sold as unsweetened baking chocolate. By adding sugar, sweetened chocolates are produced, which can be sold simply as dark chocolate, or, with the addition of milk, can be made into milk chocolate. Making chocolate with only cocoa butter and milk produces white chocolate. 
Chocolate is one of the most popular food types and flavors in the world, and many foodstuffs include chocolate, particularly desserts, including ice creams, cakes, mousse, and cookies. Many candies are filled with or coated with sweetened chocolate. Chocolate bars, either made of solid chocolate or other ingredients coated in chocolate, are eaten as snacks. Gifts of chocolate molded into different shapes (such as eggs, hearts, and coins) are traditional on certain holidays, including Christmas, Easter, Valentine''s Day, Hanukkah and Eid al-Fitr. Chocolate is also used in cold and hot beverages, such as chocolate milk, hot chocolate and chocolate liqueur.
The cacao tree was first used as a source for food in what is today Ecuador at least 5,300 years ago. Mesoamerican civilizations widely consumed cacao beverages, and in the 16th century, one of these beverages, chocolate, was introduced to Europe. Until the 19th century, chocolate was a drink consumed by societal elite. In the wake of technological advances chocolate became a mass-consumed solid food. Cocoa beans for most chocolate are grown in West African countries, particularly Ivory Coast and Ghana, which contribute about 60% of the world''s cocoa supply.', image_url = 'https://damecacao.com/wp-content/uploads/2022/09/15.-Chocolate-Ingredients-Checklist-1020x680.jpg' WHERE slug = 'chocolate';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://slidetodoc.com/presentation_image_h/764ce84829e667580777941f3d89a1b2/image-2.jpg' WHERE slug = 'raising-agents-450-i';
UPDATE ingredient SET public_summary = 'Purified water is water that has been mechanically filtered or processed to remove impurities and make it suitable for use. Distilled water was the most common form of purified water but water is more frequently purified by other processes including capacitive deionization, reverse osmosis, carbon filtering, microfiltration, ultrafiltration, ultraviolet oxidation, or electrodeionization. Combinations of a number of these processes have come into use to produce ultrapure water of such high purity that its trace contaminants are measured in parts per billion (ppb) or parts per trillion (ppt). 
Purified water has many uses, largely in the production of medications, in science and engineering laboratories and industries, and is produced in a range of purities. It is also used in the commercial beverage industry as the primary ingredient of any given trademarked bottling formula, in order to maintain product consistency. It can be produced on-site for immediate use or purchased in containers. Purified water in colloquial English can also refer to water that has been treated ("rendered potable") to neutralize, but not necessarily remove contaminants considered harmful to humans or animals.', image_url = 'https://images.openfoodfacts.org/images/products/006/827/400/0140/front_fr.3.full.jpg' WHERE slug = 'purified-water';
UPDATE ingredient SET public_summary = 'The carrot (Daucus carota subsp. sativus) is a root vegetable in the umbellifer family Apiaceae. Carrots are typically orange in colour due to their beta-carotene content, which makes them a rich source of vitamin A. Heirloom variants may be white, yellow, red, purple, or black. They are biennial plants.
The vegetable is a domesticated form of the wild carrot, native to Europe and Southwestern Asia. The domesticated plant probably originated in Iran where it was cultivated for its leaves and seeds. In 2022, world production of carrots (combined with turnips) topped 42 million tonnes, with China producing 44% of the total.
During the Second World War, a myth that carrots help people see in the dark was spread as propaganda to explain British pilots'' ability to fight in the dark; the real explanation was the introduction of radar.', image_url = 'https://www.alphafoodie.com/wp-content/uploads/2025/02/Roasted-Carrots-A-photo-of-the-ingredients-for-making-roasted-carrots-768x512.jpg' WHERE slug = 'carrot';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://pipingpotcurry.com/wp-content/uploads/2024/05/Ground-Cardamom-powder-Piping-Pot-Curry-.jpg' WHERE slug = 'cardamom-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.royal-ingredients.com/wp-content/uploads/2026/03/Potato-Starch-1.png' WHERE slug = 'potato-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.healthonics.healthcare/wp-content/uploads/2020/08/PRESERVATIVE-1-724x1024.webp' WHERE slug = 'preservative-ins-202';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://s.alicdn.com/@sc02/kf/A5fef4e5f85b44d13b2313356313847d8Z.jpg' WHERE slug = 'wheat-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://static.vecteezy.com/system/resources/previews/065/635/302/non_2x/turmeric-roots-and-powder-showcasing-natural-food-ingredients-photo.jpg' WHERE slug = 'turmeric-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.healthonics.healthcare/wp-content/uploads/2020/08/PRESERVATIVE-1-724x1024.webp' WHERE slug = 'preservatives-ins-202';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thefirstyearblog.com/wp-content/uploads/2024/05/Vanilla-Cake-Ingredients-1024x1536.png' WHERE slug = 'vanilla-cake';
UPDATE ingredient SET public_summary = 'Wheat is a group of wild and domesticated grasses of the genus Triticum (). As cereals, they are cultivated for their grains, which are staple foods around the world. Well-known wheat species and hybrids include the most widely grown common wheat (T. aestivum), spelt, durum, emmer, einkorn, and Khorasan or Kamut. The archaeological record suggests that wheat was first cultivated in the regions of the Fertile Crescent around 9600 BC.
Wheat is grown on a larger area of land than any other food crop (219.5 million hectares or 542 million acres in 2024). World trade in wheat is greater than that of all other crops combined. In 2024, world wheat production was 799 million tonnes (881 million short tons), making it the second most-produced cereal after maize (known as corn in North America and Australia). Since 1960, world production of wheat and other grain crops has tripled and is expected to grow further through the middle of the 21st century. Global demand for wheat is increasing because of the usefulness of gluten to the food industry.
Wheat is an important source of carbohydrates. Globally, it is the leading source of vegetable proteins in human food, having a protein content of about 13%, which is relatively high compared to other major cereals but relatively low in protein quality (supplying essential amino acids). When eaten as the whole grain, wheat is a source of multiple nutrients and dietary fibre. In a small part of the general population, gluten – which comprises most of the protein in wheat – can trigger coeliac disease, noncoeliac gluten sensitivity, gluten ataxia, and dermatitis herpetiformis.', image_url = 'https://img.freepik.com/premium-photo/whole-grain-bread-wheat-ingredients-white-background_928695-42191.jpg' WHERE slug = 'wheat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodsure.co.in/wp-content/uploads/2025/07/Understanding-Emulsifiers-And-Stabilizers-In-Food-Formulation-1024x683.jpg' WHERE slug = 'stabilizer-ins-440';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg38pyTkWuMEnKaCzqg-3Vs3SnRLU_ZfhMD5chqT_pZ8Z7U37YchN3eRCeslJqWHIZbCnV9ocQSQZ-qs3syhrnRILn1CUM4i7V9jp5Md5lp0yczf02oa5pZ-SYDn2EzouM5kpG4UNf9FeIF/s1600/Food+Emulsifier+types.PNG' WHERE slug = 'emulsifier-ins-473';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/I/51Hv5xUb68L._SL1000_.jpg' WHERE slug = 'artificial-vanilla-cake-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.marthastewart.com/thmb/wjFY10XXe6Nj7X3V5unOs-7K0Wc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ms-tamarind-pods-getty-534d3949221641de9173058d038b0020.jpg' WHERE slug = 'tamarind';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://kinesiologyzone.com/wp-content/uploads/2018/02/photo-1125x1500.jpg' WHERE slug = 'apple-cider-vinegar';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://khni.kerry.com/wp-content/uploads/2017/06/Natural-flavors-image.jpg' WHERE slug = 'natural-flavours';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/healthy-natural-food-ingredients-with-various-type-vegetable-fruit-seeds-table-selection_857097-2358.jpg?w=996' WHERE slug = 'natural';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/rice-bran-oil-glass-with-seed-rice-white-backgroundorganic-vegetable-oil-pure-homemade-processedraw-food-ingredient-cooking-natural-good-healthlow-calories-antioxidant_301927-695.jpg' WHERE slug = 'edible-vegetable-oil-rice-bran';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://greensmoothiegourmet.com/wp-content/uploads/2023/07/ingredients-strawberry-water-text.jpg' WHERE slug = 'and-water';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodrealitycheck.com/wp-content/uploads/2025/12/E296-Malic-Acid-1536x1152.jpg' WHERE slug = 'acidity-regulators-ins-296';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://villagersmart.com/wp-content/uploads/2023/10/19925b.jpg' WHERE slug = 'toned-milk';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thecookingfoodie.com/wp-content/uploads/2025/06/Gluten-free-oat-flour-1080x1080.jpg' WHERE slug = 'oats-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://optimisingnutrition.com/wp-content/uploads/2024/06/mineral-rich-foods.png' WHERE slug = 'mineral';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://guargum.co.in/admin/public/upload/blog/1750027272430025.jpg' WHERE slug = 'stabilizers-410-412';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.ariyancorp.com/wp-content/uploads/2021/03/types-of-cooking-oils-fats_hero-768x432.jpg' WHERE slug = 'edible-vegetable-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'edible-vegetable-fat-hydrogenated';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://tiimg.tistatic.com/fp/1/008/590/100-natural-freeze-drying-mango-powder-442.jpg' WHERE slug = 'mango-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/202f0j00BWZbUwLyLizh/Food-Ingredient-Edible-Native-Maize-Corn-Starch-Powder.webp' WHERE slug = 'edible-maize-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://ingreland.com/wp-content/uploads/2025/07/Corn-Starch.jpeg' WHERE slug = 'maize-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/736x/3b/63/66/3b6366be5741891249fb9045a1b07da0.jpg' WHERE slug = 'dehydrated-potato';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/272fd8f1-4d2f-491b-9003-a13f8de0ec12.__CR0,0,970,600_PT0_SX970_V1___.png' WHERE slug = 'custard-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.abcnewsfe.com/a/1dfd5fba-7a0b-42a3-94d9-d894e4b2fcb7/black-white-sesame-seeds-gty-jt-240109_1704825893422_hpEmbed_3x2.jpg' WHERE slug = 'sesame-seeds';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/wahid-foodpackaging-190424171341/75/Food-Packaging-15-2048.jpg' WHERE slug = 'stabilizers-ins-471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://laurenfitfoodie.com/wp-content/uploads/2024/10/grits-ingredients-730x1095.png' WHERE slug = 'rice-grits';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://i.pinimg.com/originals/7b/1f/18/7b1f18bd3f097cafe2264d1c65bc660a.jpg' WHERE slug = 'roasted-peanuts';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'hydrogenated-vegetable-oils';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0950/8110/3653/files/ChatGPT_Image_Apr_29_2026_04_54_58_PM.png?v=1777461930' WHERE slug = 'hydrogenated-vegetable-fats';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/226f3j00hNJcEvAbGfom/Food-Colour-Carmine-Edible-Red-102-Ponceau-4r-Cochineal.webp' WHERE slug = 'colour-102';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.goeatgreen.com/wp-content/uploads/2025/05/vegan-green-pea-fritters-ingredients.jpg' WHERE slug = 'green-peas';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.sgr777foods.com/wp-content/uploads/2026/04/Filtered-Groundnut-Oil-Nutrition-Facts-scaled.webp' WHERE slug = 'groundnut-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodstruct.com/compareimages/rice-bran-oil-vs-palm-kernel-oil.jpg' WHERE slug = 'edible-vegetable-oil-palmolein-rice-bran-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cygluten.com/images/resources/cygluten_are_cocoa_solids_gluten_free_a_comprehensive_guide_for_chocolate_lovers_20260328_165836.png' WHERE slug = 'cocoa-solids-18';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://down-ph.img.susercontent.com/file/ph-11134207-820l4-mmsm174gxbeud4' WHERE slug = 'clove-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://slidetodoc.com/presentation_image_h/764ce84829e667580777941f3d89a1b2/image-2.jpg' WHERE slug = 'raising-agents-ins-450-i';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thebiblicalnutritionist.com/wp-content/uploads/2021/08/trans-fat-label-misleading-land-o-lakes-buttery-spread-says-zero-trans-fat-on-the-label_orig.jpg' WHERE slug = 'fractionated-vegetable-fat';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.royal-ingredients.com/wp-content/uploads/2024/09/Tapioca-Starch.png' WHERE slug = 'tapioca-starch';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'flavours-natural-and-nature-identical-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.ctfassets.net/gi8mrztylj0k/4VAm2Aj4CihcfTQPjT5reT/edcfa645967cfcd9f9ee30bb9e365cfc/Table.png' WHERE slug = 'flavour-nature-identical';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.cnmqh.com/aispk/images/20260211/698b745cd4171.png' WHERE slug = 'preservatives-ins-282';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://youreverydayfoodie.com/wp-content/uploads/2026/02/celerysalad-ingredients2.webp' WHERE slug = 'celery';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/blogs/2147508904/images/54a871d-4f4e-5ec-bd63-fa601456d1f_natural_vs_non_natural_6.png' WHERE slug = 'flavour-natural-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.allrecipes.com/thmb/rOcLPPjoJzyJRzF0us73BlLduuQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/what-is-fenugreek-2x1-c3bfc694fad948ebb1364819e6a240d4.jpg' WHERE slug = 'fenugreek';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://order.nutriversum.com/sites/hnlabs_eu/documents/SF_cut/RTG_WHEYPROTEIN_stracciatella_sf.jpg' WHERE slug = 'whey-protein-concentrate';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://runtimes.co.uk/wp-content/uploads/2024/02/e471-jpg.webp' WHERE slug = 'emulsifiers-ins-471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodrealitycheck.com/wp-content/uploads/2025/12/E296-Malic-Acid-1536x1152.jpg' WHERE slug = 'acidity-regulator-ins-296';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.cnadditives.com/uploads/31598/pgpr-e476-food-emulsifier-applications13e02.jpg' WHERE slug = 'emulsifiers-322-476';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.navafresh.io/products/HAAZINB0B4SJ2VYL/1_41RKp-CSoNL_desktop.jpg' WHERE slug = 'thickeners-ins-414-ins-418';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://youreverydayfoodie.com/wp-content/uploads/2025/12/caramelizedbakedbananaslices-ingredients3.webp' WHERE slug = 'banana';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://s.alicdn.com/@sc02/kf/A7325bf26fecd461ab4ea57163d4d3837D.jpg' WHERE slug = 'bakery-shortening';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://rukminim2.flixcart.com/image/960/1280/xif0q/baking-ingredient/p/n/x/250-soy-lecithin-powder-e322-250g-soya-lecithin-emulsifier-original-imahgfxfhwjyqrue.jpeg?q=60' WHERE slug = 'emulsifier-ins-322-from-soy';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://insanelygoodrecipes.com/wp-content/uploads/2022/10/Olive-Oil-Recipes-1-768x1152.jpg' WHERE slug = 'olive-oil';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodbabe.com/app/uploads/2018/05/difference-between-artificial-and-natural-flavors.jpg' WHERE slug = 'nature-identical-and-artificial-vanilla-cake-flavouring-substances';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00eokqAQTcZuob/Food-Emulsifiers-of-Distilled-Monoglyceride-DMG-Chemical-Ingredient-Row-Powder.jpg' WHERE slug = 'emulsifier-e471';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.made-in-china.com/2f0j00mGyoBnZgiFuO/100-Natural-Food-Ingredient-Hordeum-Vulgare-Malt-Extract-Barley-Malt-Extract-Powder.webp' WHERE slug = 'barley-malt-extract';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://gallerychef.com/wp-content/uploads/2022/11/AdobeStock_177136730-1.jpg' WHERE slug = 'nutmeg';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.health.nsw.gov.au/heal/PublishingImages/sweeteners-label.png' WHERE slug = 'sweeteners-955';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://gr8lifeceo.com/wp-content/uploads/2021/04/stevia-sweetleaf-800x524.png' WHERE slug = 'stevia';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn1.vectorstock.com/i/1000x1000/77/25/food-antioxidants-acidity-regulators-vector-6347725.jpg' WHERE slug = 'acidity-regulators-ins-296-ins-330';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh6Yb-Q5kwb6G3TXkwx8xaF7zW6axHlrpxaNWjFIjS53EXsfhJeyfvbyputTwJuhxvfzmP87nlGDxoYlDnWiG0gkcj-GJJAehwwp0F-pzpxbjTKRjWCkKe998mFL3AysM2zSiK_/s1600/IMG_20180626_114245.jpg' WHERE slug = '331-iii';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.cnchemsino.com/foodingredients/wp-content/uploads/2025/03/Xanthan-Gum-Price-E415-Stabilizer-Food-Grade.jpg' WHERE slug = 'stabilizer-ins-415';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://apal.org.au/wp-content/uploads/2019/08/Yoghurt-covered-blueberries-glazing-agent-904-circled-600px.jpg' WHERE slug = 'edible-common-salt-and-glazing-agent-904';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.microingredients.com/cdn/shop/files/WholeMilk_2_1800x1800.jpg?v=1705452510' WHERE slug = 'milk-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://c8.alamy.com/comp/2WAYPG7/a-bowl-of-vibrant-fresh-mint-leaves-a-key-aromatic-ingredient-for-culinary-dishes-on-a-kitchen-countertop-2WAYPG7.jpg' WHERE slug = 'mint-leaves';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodpowderindia.com/wp-content/uploads/2024/06/ginger1.jpg' WHERE slug = 'dried-ginger-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.stcharlestrading.com/wp-content/uploads/2024/09/Soy-Flour-1024x640.png' WHERE slug = 'soya-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://foodsure.co.in/wp-content/uploads/2025/07/Understanding-Emulsifiers-And-Stabilizers-In-Food-Formulation.jpg' WHERE slug = 'stabiliser-1400';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.zeptonow.com/production/ik-seo/tr:w-470,ar-5873-6656,pr-true,f-auto,q-40,dpr-2/cms/product_variant/f0f79651-d751-4456-9f80-cb7a231a4591/Zuari-Foods-Maida-Refined-Wheat-Flour.jpeg' WHERE slug = 'maida-refined-wheat-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://plantempoweredkitchen.com/wp-content/uploads/2023/04/10-healthy-soy-foods-3.jpg' WHERE slug = 'soy';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://cdn.shopify.com/s/files/1/0277/8103/8115/products/original5.2096802.1_525x700.jpg?v=1576535048' WHERE slug = 'soy-protein-isolate';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/06/jowar-uttapam-ingredients-1152x1536.jpg' WHERE slug = 'jowar-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.deliaonline.com/sites/default/files/styles/3_by_2/public/quick_media/ingredient-puddings-cream.jpg' WHERE slug = 'cream';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://wholesomemadeeasy.com/wp-content/uploads/2021/07/Mango-Smoothie-Ingredients-1093x1536.jpg' WHERE slug = 'mango';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://plantbasedfolk.com/wp-content/uploads/2022/12/Black-Sesame-Cookies-Ingredients.jpg' WHERE slug = 'sesame';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.southernliving.com/thmb/DFSrycHBnAwcW6el1tF42VNQuEU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/CreamedCornGrits_Audit7678_Step_1_278-e1f2add378c74c9d86e7a05c98bc82c9.jpg' WHERE slug = 'corn-grits';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://thericechick.com/wp-content/uploads/2022/06/overnight-rice-flakes-ingredients.jpg' WHERE slug = 'rice-flakes';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.alcofoods.com/cdn/shop/products/Coriander01_1445x.jpg?v=1662370613' WHERE slug = 'coriander-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://5.imimg.com/data5/SELLER/Default/2024/5/421834486/YI/PA/VQ/61275056/4kg-peanut-flour-500x500.png' WHERE slug = 'high-protein-peanut-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thumbs.dreamstime.com/z/coffee-nutrition-facts-cup-plant-branch-label-55357773.jpg' WHERE slug = 'coffee-0-8';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://down-my.img.susercontent.com/file/my-11134207-820lb-mghhj3l1s3yn65' WHERE slug = 'humectant-glycerine';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://thumbs.dreamstime.com/b/green-cardamom-pods-powder-wooden-bowl-spoon-aromatic-spice-ingredient-cooking-culinary-dishes-food-preparation-natural-402564214.jpg' WHERE slug = 'green-cardamom';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://coconutseller.in/wp-content/uploads/2024/07/82b43823-b31e-4d8e-904f-84d5d24ba950.jpg?v=1722227814' WHERE slug = 'coconut';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://pbs.twimg.com/media/EECtPNBXoAABmnk.jpg' WHERE slug = 'added-water';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'http://www.nutrientsreview.com/wp-content/uploads/2014/09/Foods-High-in-Fructooligosaccharides-FOS.jpg' WHERE slug = 'fructo-oligosaccharides';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/fresh-spicy-red-chili-ingredient-background-dark-textured-surface-ai-generated_1078402-32631.jpg' WHERE slug = 'red-chillies';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://img.freepik.com/premium-photo/cinnamon-powder-close-up-food-condiment-spice-obtained-from-arvora-bark-used-sweet-savory-foods_72932-2339.jpg' WHERE slug = 'cinnamon-powder';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/secb-sem4phya20-21-0199-arnabkumarsamanta-211130160101/75/FOOD-ADDITIVES-USED-IN-BAKERY-PRODUCT-5-2048.jpg' WHERE slug = 'flour-treatment-agent-ins-223';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/container-of-the-food-additive-e903-wladimir-bulgarscience-photo-library.jpg' WHERE slug = 'glazing-agent-ins-903';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.spoonforkbacon.com/wp-content/uploads/2023/10/baked-mac-cheese-ingredients.jpg' WHERE slug = 'cheese';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://www.hangrypants.com/wp-content/uploads/2024/12/8629b82994058dbb/flavoring-ingredients.jpeg' WHERE slug = 'flavourings';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://mygoodfoodworld.com/wp-content/uploads/2023/12/Chana-dal-fry-recipe-ingredients-768x960.jpg' WHERE slug = 'chana-dal';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://images.news18.com/ibnlive/uploads/2026/10/Firefly_Gemini-Flash_Ragi-Ladoo__Ragi-is-a-good-source-of-fibre-and-contains-calcium-and-other-nutrients.-305474-2026-10-548d12450335dc6b14bc13201cac3196.png' WHERE slug = 'ragi-flour';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/noodlesproject-160530152234/95/personal-study-of-18-noodle-products-of-7-companies-in-india-29-638.jpg?cb=1465722507' WHERE slug = 'flavour-enhancers-ins-627-and-ins-631';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image4.slideserve.com/334507/glazing-agent-l.jpg' WHERE slug = 'glazing-agent-ins-93';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://get.pxhere.com/photo/food-cashew-nut-ingredient-nuts-seeds-cuisine-Cashew-family-plant-produce-mixed-nuts-dish-peanut-superfood-legume-1627044.jpg' WHERE slug = 'cashew';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://m.media-amazon.com/images/I/41kGL4IT0aL._UF1000,1000_QL80_.jpg' WHERE slug = 'flavour-enhancer-ins-635';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://c8.alamy.com/comp/3BDCT0A/e516-calcium-sulphate-a-firming-agent-and-coagulant-used-in-tofu-production-and-as-a-flour-treatment-agent-3BDCT0A.jpg' WHERE slug = 'flour-treatment-agent-516';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://wholesalehealthfood.com.au/wp-content/uploads/2024/07/Calcium-Carbonate-ORGANIC-FOOD-GRADE-PREMIUM-Powder-850x850.png' WHERE slug = 'calcium-carbonate';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://image.slidesharecdn.com/foodpreservatives-240407122904-6908d347/85/Food-preservation-hzhzgdskbxhzk-AZ-gxjd-11-320.jpg' WHERE slug = 'permitted-class-ii-preservative-ins-211';
UPDATE ingredient SET public_summary = 'No verified summary currently available for this ingredient.', image_url = 'https://ingreland.com/wp-content/uploads/2026/01/pectin-types-comparison-guide-germany.png' WHERE slug = 'pectin';