"""Add safety limit fields

Revision ID: 1b01648f8b15
Revises: 96549ade4e02
Create Date: 2026-10-07 12:25:04.569124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b01648f8b15'
down_revision: Union[str, Sequence[str], None] = '96549ade4e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_safety_violation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('violation_details', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('variant_source')
    op.drop_table('admin_user')
    op.drop_table('alternative')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_review_task_status_assigned_due'), table_name='review_task')
    op.drop_table('review_task')
    op.drop_index(op.f('ix_correction_report_status_created'), table_name='correction_report')
    op.drop_table('correction_report')
    op.add_column('ingredient', sa.Column('daily_limit_amount', sa.Numeric(), nullable=True))
    op.add_column('ingredient', sa.Column('daily_limit_unit', sa.String(), nullable=True))
    op.add_column('ingredient', sa.Column('is_generally_safe', sa.Boolean(), nullable=True))
    op.add_column('rating', sa.Column('color_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'color_status')
    op.drop_column('ingredient', 'is_generally_safe')
    op.drop_column('ingredient', 'daily_limit_unit')
    op.drop_column('ingredient', 'daily_limit_amount')
    op.create_table('correction_report',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('public_reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reporter_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('evidence_asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('correction_report_pkey')),
    sa.UniqueConstraint('public_reference', name=op.f('correction_report_public_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_correction_report_status_created'), 'correction_report', ['status', 'created_at'], unique=False)
    op.create_table('review_task',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('review_task_pkey'))
    )
    op.create_index(op.f('ix_review_task_status_assigned_due'), 'review_task', ['status', 'assigned_to', 'due_at'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_member_pkey')),
    sa.UniqueConstraint('slug', name=op.f('team_member_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alternative',
    sa.Column('source_variant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alternative_variant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alternative_variant_id'], ['product_variant.id'], name=op.f('alternative_alternative_variant_id_fkey')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], name=op.f('alternative_methodology_version_id_fkey')),
    sa.ForeignKeyConstraint(['source_variant_id'], ['product_variant.id'], name=op.f('alternative_source_variant_id_fkey')),
    sa.PrimaryKeyConstraint('source_variant_id', 'alternative_variant_id', 'methodology_version_id', name=op.f('alternative_pkey'))
    )
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth_subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_user_pkey')),
    sa.UniqueConstraint('email', name=op.f('admin_user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('variant_source',
    sa.Column('label_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('locator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_version.id'], name=op.f('variant_source_label_version_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('variant_source_source_id_fkey')),
    sa.PrimaryKeyConstraint('label_version_id', 'source_id', 'field_path', name=op.f('variant_source_pkey'))
    )
    op.drop_table('rating_safety_violation')
    # ### end Alembic commands ###
