"""Add workflow and governance models

Revision ID: 39f3771cab95
Revises: 
Create Date: 2026-09-18 12:25:22.554486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f3771cab95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('auth_subject', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scoring_profile_id', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('correction_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_reference', sa.String(), nullable=False),
    sa.Column('reporter_contact', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('evidence_asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_reference')
    )
    op.create_index('ix_correction_report_status_created', 'correction_report', ['status', 'created_at'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('INS_number', sa.String(), nullable=True),
    sa.Column('E_number', sa.String(), nullable=True),
    sa.Column('ingredient_type', sa.String(), nullable=True),
    sa.Column('technical_function', sa.String(), nullable=True),
    sa.Column('public_summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('market',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('regulator_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    op.create_table('methodology_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('review_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_task_status_assigned_due', 'review_task', ['status', 'assigned_to', 'due_at'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('archived_url', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('team_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('photo_asset_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingredient_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('effect_type', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('dose_context', sa.String(), nullable=True),
    sa.Column('evidence_grade', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('regulatory_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('use_category', sa.String(), nullable=False),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('max_level', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'market_id', 'use_category', 'effective_from', name='uq_regulatory_status_ingredient_market_category_date')
    )
    op.create_index('ix_regulatory_status_market_effective', 'regulatory_status', ['ingredient_id', 'market_id', 'effective_from'], unique=False)
    op.create_table('evidence_source',
    sa.Column('ingredient_evidence_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('locator', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_evidence_id'], ['ingredient_evidence.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('ingredient_evidence_id', 'source_id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('local_name', sa.String(), nullable=True),
    sa.Column('pack_quantity', sa.Numeric(), nullable=True),
    sa.Column('pack_unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_variant_market_gtin', 'product_variant', ['market_id', 'gtin'], unique=True, postgresql_where=sa.text('gtin IS NOT NULL'))
    op.create_table('alternative',
    sa.Column('source_variant_id', sa.UUID(), nullable=False),
    sa.Column('alternative_variant_id', sa.UUID(), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alternative_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], ),
    sa.ForeignKeyConstraint(['source_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('source_variant_id', 'alternative_variant_id', 'methodology_version_id')
    )
    op.create_table('label_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('ingredients_raw', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('serving_quantity', sa.Numeric(), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('label_image_id', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_label_version_variant_version', 'label_version', ['variant_id', 'version_no'], unique=True)
    op.create_table('nutrition_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label_version_id', sa.UUID(), nullable=False),
    sa.Column('basis_quantity', sa.Numeric(), nullable=True),
    sa.Column('basis_unit', sa.String(), nullable=True),
    sa.Column('energy', sa.Numeric(), nullable=True),
    sa.Column('fat', sa.Numeric(), nullable=True),
    sa.Column('saturated_fat', sa.Numeric(), nullable=True),
    sa.Column('trans_fat', sa.Numeric(), nullable=True),
    sa.Column('carbohydrate', sa.Numeric(), nullable=True),
    sa.Column('sugars', sa.Numeric(), nullable=True),
    sa.Column('added_sugars', sa.Numeric(), nullable=True),
    sa.Column('protein', sa.Numeric(), nullable=True),
    sa.Column('fibre', sa.Numeric(), nullable=True),
    sa.Column('sodium', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_version_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label_version_id', sa.UUID(), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('nutrition_score', sa.Integer(), nullable=True),
    sa.Column('ingredient_score', sa.Integer(), nullable=True),
    sa.Column('context_score', sa.Integer(), nullable=True),
    sa.Column('confidence_grade', sa.String(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_version.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_version_id', 'methodology_version_id', name='uq_rating_label_methodology')
    )
    op.create_table('variant_source',
    sa.Column('label_version_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('locator', sa.String(), nullable=True),
    sa.Column('verification_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['label_version_id'], ['label_version.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('label_version_id', 'source_id', 'field_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_source')
    op.drop_table('rating')
    op.drop_table('nutrition_facts')
    op.drop_index('ix_label_version_variant_version', table_name='label_version')
    op.drop_table('label_version')
    op.drop_table('alternative')
    op.drop_index('ix_product_variant_market_gtin', table_name='product_variant', postgresql_where=sa.text('gtin IS NOT NULL'))
    op.drop_table('product_variant')
    op.drop_table('evidence_source')
    op.drop_index('ix_regulatory_status_market_effective', table_name='regulatory_status')
    op.drop_table('regulatory_status')
    op.drop_table('product')
    op.drop_table('ingredient_evidence')
    op.drop_table('team_member')
    op.drop_table('source')
    op.drop_index('ix_review_task_status_assigned_due', table_name='review_task')
    op.drop_table('review_task')
    op.drop_table('methodology_version')
    op.drop_table('market')
    op.drop_table('ingredient')
    op.drop_index('ix_correction_report_status_created', table_name='correction_report')
    op.drop_table('correction_report')
    op.drop_table('category')
    op.drop_table('brand')
    op.drop_table('audit_log')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
