solid:
- points: 0
  energy_lte: 80
  sat_fat_lte: 1.0
  sugars_lte: 4.2
  sodium_lte: 90
  fv_lte: 10
  nlm_lte: 10
  fibre_lte: 3
  protein_lte: 1.5
- points: 1
  energy_gt: 80
  sat_fat_gt: 1.0
  sugars_gt: 4.2
  sodium_gt: 90
  fv_gt: 10
  nlm_gt: 10
  fibre_gt: 3
  protein_gt: 1.5
- points: 2
  energy_gt: 160
  sat_fat_gt: 2.0
  sugars_gt: 8.4
  sodium_gt: 180
  fv_gt: 15
  nlm_gt: 15
  fibre_gt: 6
  protein_gt: 2.0
- points: 3
  energy_gt: 240
  sat_fat_gt: 3.0
  sugars_gt: 12.6
  sodium_gt: 270
  fv_gt: 20
  nlm_gt: 20
  fibre_gt: 9
  protein_gt: 2.5
- points: 4
  energy_gt: 320
  sat_fat_gt: 4.0
  sugars_gt: 16.8
  sodium_gt: 360
  fv_gt: 25
  nlm_gt: 25
  fibre_gt: 12
  protein_gt: 3.0
- points: 5
  energy_gt: 400
  sat_fat_gt: 5.0
  sugars_gt: 21.0
  sodium_gt: 450
  fv_gt: 30
  nlm_gt: 30
  fibre_gt: 15
  protein_gt: 5.0
- points: 6
  energy_gt: 480
  sat_fat_gt: 6.0
  sugars_gt: 25.2
  sodium_gt: 540
  fv_gt: 35
  nlm_gt: 35
  fibre_gt: 18
  protein_gt: 7.0
- points: 7
  energy_gt: 560
  sat_fat_gt: 7.0
  sugars_gt: 29.4
  sodium_gt: 630
  fv_gt: 40
  nlm_gt: 40
  fibre_gt: 21
  protein_gt: 10.0
- points: 8
  energy_gt: 640
  sat_fat_gt: 8.0
  sugars_gt: 33.6
  sodium_gt: 720
  fv_gt: 45
  nlm_gt: 45
  fibre_gt: 24
  protein_gt: 15.0
- points: 9
  energy_gt: 720
  sat_fat_gt: 9.0
  sugars_gt: 37.8
  sodium_gt: 810
  fv_gt: 50
  nlm_gt: 50
  fibre_gt: 27
  protein_gt: 20.0
- points: 10
  energy_gt: 800
  sat_fat_gt: 10.0
  sugars_gt: 42.0
  sodium_gt: 900
  fv_gt: 55
  nlm_gt: 55
  fibre_gt: 30
  protein_gt: 25.0
- points: 11
  sat_fat_gt: 12
  sugars_gt: 46.2
  sodium_gt: 990
  protein_gt: 30.0
- points: 12
  sat_fat_gt: 14
  sugars_gt: 50.4
  sodium_gt: 1080
  protein_gt: 35.0
- points: 13
  sat_fat_gt: 16
  sugars_gt: 54.6
  sodium_gt: 1170
  protein_gt: 40.0
- points: 14
  sat_fat_gt: 18
  sugars_gt: 58.8
  sodium_gt: 1260
  protein_gt: 45.0
- points: 15
  sat_fat_gt: 20
  sugars_gt: 63.0
  sodium_gt: 1350
  protein_gt: 50.0
- points: 16
  sat_fat_gt: 22
  sugars_gt: 67.2
  sodium_gt: 1440
- points: 17
  sat_fat_gt: 24
  sugars_gt: 71.4
  sodium_gt: 1530
- points: 18
  sat_fat_gt: 26
  sugars_gt: 75.6
  sodium_gt: 1620
- points: 19
  sat_fat_gt: 28
  sugars_gt: 79.8
  sodium_gt: 1710
- points: 20
  sat_fat_gt: 30
  sugars_gt: 84.0
  sodium_gt: 1800
- points: 21
  sat_fat_gt: 32
  sodium_gt: 1890
- points: 22
  sat_fat_gt: 34
  sodium_gt: 1980
- points: 23
  sat_fat_gt: 36
  sodium_gt: 2070
- points: 24
  sat_fat_gt: 38
  sodium_gt: 2160
- points: 25
  sat_fat_gt: 40
  sodium_gt: 2250
liquid:
- points: 0
  energy_lte: 6
  sugars_lte: 0.1
  fv_lte: 5
  protein_lte: 1.5
- points: 1
  energy_gt: 6
  sugars_gt: 0.1
  fv_gt: 5
  protein_gt: 1.5
- points: 2
  energy_gt: 12
  sugars_gt: 1.6
  fv_gt: 10
  protein_gt: 2.0
- points: 3
  energy_gt: 18
  sugars_gt: 3.1
  fv_gt: 15
  protein_gt: 2.5
- points: 4
  energy_gt: 24
  sugars_gt: 4.6
  fv_gt: 20
  protein_gt: 3.0
- points: 5
  energy_gt: 30
  sugars_gt: 6.1
  fv_gt: 25
  protein_gt: 5.0
- points: 6
  energy_gt: 36
  sugars_gt: 7.6
  fv_gt: 30
  protein_gt: 7.0
- points: 7
  energy_gt: 42
  sugars_gt: 9.1
  fv_gt: 35
  protein_gt: 10.0
- points: 8
  energy_gt: 48
  sugars_gt: 10.6
  fv_gt: 40
  protein_gt: 15.0
- points: 9
  energy_gt: 54
  sugars_gt: 12.1
  fv_gt: 45
  protein_gt: 20.0
- points: 10
  energy_gt: 60
  sugars_gt: 13.6
  fv_gt: 55
  protein_gt: 25.0
- points: 11
  protein_gt: 30.0
- points: 12
  protein_gt: 35.0
- points: 13
  protein_gt: 40.0
- points: 14
  protein_gt: 45.0
- points: 15
  protein_gt: 50.0
